{
  "hash": "7bed82d150f7d571f7f206555f06f869",
  "result": {
    "engine": "knitr",
    "markdown": "---\nexecute:\n  freeze: auto\nfig-width: 5\nfig-asp: 0.75\neditor:\n  markdown:\n    wrap: 72\neditor_options:\n  chunk_output_type: console\n---\n\n# Model formulation and parameter estimation {#sec-estimation}\n\n## List of the main functions used in the chapter {.unnumbered}\n\n| Function | R Package | Used for |\n|------------------------|------------------------|------------------------|\n| `lmer()` | *lme4* | Fitting linear mixed models |\n| `glmer()` | *lme4* | Fitting generalized linear mixed models |\n| `glgpm()` | *RiskMap* | Fitting generalized linear geostatistical models |\n| `variogram()` | *RiskMap* | Computing the empirical variogram and carrying out permutation test for spatial independence |\n\nThis chapter introduces the process of moving from exploratory analysis\nto the formal specification of statistical models, through to parameter\nestimation and interpretation of results. We first outline the main\nsteps involved, highlight the role of covariates, and present simple\napproaches for exploring and modelling non-linear relationships. We then\nturn to the assessment of residual spatial correlation, which motivates\nthe use of geostatistical models, and describe how maximum likelihood\nmethods can be applied for their estimation.\n\n## Exploratory analysis\n\nAs illustrated in @fig-stages, exploratory analysis is the first step in\nany statistical analysis. This stage is crucial for guiding how\ncovariates should be incorporated into the model and for assessing\nwhether the remaining unexplained variation exhibits spatial\ncorrelation. In the case of count data, this stage also involves\nexamining the presence of *overdispersion*, a phenomenon that often\narises when important covariates are omitted or when there is\nunaccounted heterogeneity in the data. In the following sections, we\nexplain what overdispersion is in more detail and why checking for its\npresence is an essential prerequisite before fitting geostatistical\nmodels to count data.\n\n### Exploring associations with risk factors using count data {#sec-expl-assoc}\n\nAssessment of the association between the health outcome of interest and\nnon-categorical (i.e. continuous) risk factors can be carried out using\ngraphical tools, such as scatter plots. The graphical inspection of the\nempirical association between the outcome and the covariates is\nespecially useful to identify non-linear patterns in the relationship\nwhich should then be accounted for in the model formulation.\n\nIn this section, we focus on the case where the observed outcome is a\ncount, which requires a different treatment from continuously measured\noutcomes. The latter have been extensively discussed in the statistical\nliterature and are covered in most standard textbooks (see, for example,\nChapter 1 of @weisberg2014).\n\n#### When the outcome is an aggregated count {#sec-agg-count-exp}\n\nLet us first consider the example of the river-blindness data in Liberia\n(@sec-rb-ch1), and examine the association between prevalence and\nelevation. We first generate a plot of the prevalence against the\nmeasured elevation at each of the sample locations\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute prevalence\nliberia$prev <- liberia$npos / liberia$ntest\n\n# Scatterplot of prevalence vs. elevation\nggplot(liberia, aes(x = elevation, y = prev)) +\n  geom_point() +\n  labs(x = \"Elevation (meters)\", y = \"Prevalence\")\n```\n\n::: {.cell-output-display}\n![Scatter plot of the empirical prevalence for river-blindess against elevation, measured in meters.](03_model-fitting_files/figure-html/fig-prev-elev-liberia-1.png){#fig-prev-elev-liberia}\n:::\n:::\n\n\nThe plot shown in @fig-prev-elev-liberia shows that, as elevation\nincreases from 0 to around 150 meters, prevalence rapidly increases to\naround 0.25 and, for larger values in elevation than 150 meters, the\nrelationship levels off. How can we account for this in a regression\nmodel? To answer this question rigorously, the plot in\n@fig-prev-elev-liberia cannot be used. This is because, when the\nmodelled outcome is a bounded Binomial count, regression relationships\nare usually specified on the logit-transformed prevalence (log-odds)\nscale; see @tbl-glm in Section @sec-geostat-models. To explore\nregression relationships in the case of prevalence data, it is\nconvenient to use the so-called empirical logit in place of the\nempirical prevalence. The empirical logit is defined as\n$$\nl_{i} = \\log\\left\\{\\frac{y_i + 1/2}{n_i - y_i + 1/2}\\right\\}\n$$ {#eq-empirical-logit}\n\nwhere $y_i$ denotes the number of individuals who tested positive for\nriver-blindness and $n_i$ is the total number of people tested at\nlocation $i$. Rather than applying the standard logit transformation to\nthe empirical prevalence, we use the empirical logit transformation,\nimplemented via the `elogit()` function in the RiskMap package. This\ntransformation introduces a small adjustment to both the numerator and\ndenominator, ensuring that the transformed values remain finite even\nwhen the observed prevalence is exactly 0 or 1, for which the standard\nlogit is undefined.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Empirical logit transformation\nliberia$elogit <- elogit(y = liberia$npos, m = liberia$ntest)\n\n# Scatterplot of elogit vs. elevation with different potential models\nggplot(liberia, aes(x = elevation, y = elogit)) +\n  geom_point() +\n\n  # Adding a smoothing spline\n  geom_smooth(method = \"gam\", formula = y ~ s(x), se = FALSE) +\n\n  # Adding linear regression fit with log-transformed elevation\n  geom_smooth(\n    method = \"lm\", formula = y ~ log(x),\n    col = \"darkgreen\", lty = \"dashed\", se = FALSE\n  ) +\n\n  # Adding linear regression fit with change point in 150 meters\n  geom_smooth(\n    method = \"lm\", formula = y ~ x + pmax(x - 150, 0),\n    col = \"orange\", lty = \"dashed\", se = FALSE\n  ) +\n  labs(x = \"Elevation (meters)\", y = \"Empirical logit\")\n```\n\n::: {.cell-output-display}\n![Scatter plot of the empirical prevalence for river-blindess against elevation, measured in meters.](03_model-fitting_files/figure-html/fig-elogit-elev-liberia-1.png){#fig-elogit-elev-liberia}\n:::\n:::\n\n\n@fig-elogit-elev-liberia shows the scatter plot of the empirical logit\nagainst elevation. In this plot, we have also added three curves through\nthe `geom_smooth()` function from the ggplot2 package. Using this\nfunction, we first specify `method = \"gam\"` to add a penalized smoothing\nspline [@Wood2017-ad], represented by the blue solid line. The smoothing\nspline allows us to better discern the type of relationship and how to\nbest capture it using a standard regression approach. As we can see from\n@fig-elogit-elev-liberia, the smoothing spline corroborates our initial\nobservation of a positive relationship up to about 150 meters, followed\nby a plateau.\n\nTo capture this non-linear relationship, we can use the two following\napproaches. The first is based on a simple log-transformation of\nelevation and is represented in @fig-elogit-elev-liberia by the green\nline. If we express this relationship using a standard Binomial\nregression model, this would take the form\n$$\n\\log\\left\\{\\frac{p(x_i)}{1-p(x_i)}\\right\\} = \\beta_0 + \\beta_1 \\log\\{d(x_i)\\}\n$$ {#eq-log-elev-glm}\nwhere $p(x_i)$ denote the the probability of\nriver-blindness infection at sampled location $x_i$, and $d(x_i)$ is the\nelevation at that location.\n\nAlternatively, the non-linear effect of elevation on prevalence could be\ncaptured using a linear spline. Put in simple terms, we want to fit a\nlinear regression model that allows for a change in slope above 150\nmeters. Formally, this is expressed in a Binomial regression model as\n$$\n\\log\\left\\{\\frac{p(x_i)}{1-p(x_i)}\\right\\} = \\beta_0 + \\beta_1 d(x_i) + \\beta_{2} \\max\\{d(x_i)-150, 0\\}.\n$$ {#eq-lspline-elev-glm}\nBased on the equation above, the effect of\nelevation below 150 meters is quantified by the parameter $\\beta_1$.\nAbove 150 meters, instead, the effect of elevation becomes\n$\\beta_1 + \\beta_2$. Note that the function `pmax()` (and not the\nstandard base function `max()`) should be used in R when the computation\nof the maximum between a scalar value and each of the components of a\nnumeric vector is required.\n\nBefore proceeding further, it is important to explain the differences\nbetween the use of the logarithmic transformation (@eq-log-elev-glm) and\nthe linear spline (@eq-lspline-elev-glm). We observe that both curves\nprovide a similar fit to the data, with larger differences observed for\nlarger values in elevation, where the log-transformed elevation models\nyield larger values for the predicted prevalence. This also suggests\nthat if we were to extrapolate the predictions beyond 600 meters in\nelevation the implied pattern by the model with the log-transformed\nelevation would predict an increasingly larger elevation, which is\nunrealistic, since the fly that transmits the disease cannot breed at\nthose altitudes. The linear spline model instead would generate\npredictions that would be very similar to those observed between 150 and\n600 meters. From this point of view, the linear spline model would thus\nhave more scientific validity than the other model. However, which of\nthe two approaches should be chosen to model the effect of elevation is\na question that closely depends on the research question to be\naddressed.\n\nIf the interest of the study was in better understanding the association\nbetween elevation and prevalence, the linear spline model does not only\nprovide a more credible explanation but also its regression parameters\ncan be more easily interpreted. In fact, for a unit increase in\nelevation, the multiplicative change in the odds for river-blindness is\n$\\exp\\{\\beta_1\\}$, if elevation is below 150 meters, and\n$\\exp\\{\\beta_1+\\beta_2\\}$, if elevation is above 150 meters. When\ninstead we use the log-transformed elevation, the interpretation of\n$\\beta_1$ in @eq-log-elev-glm is more complicated, as it is based on the\nmultiplicative increase in elevation by the same amount given by the\nbase of the algorithm, which is about $e \\approx 2.718$. To avoid this,\none could rescale the regression coefficient as, for example,\n$\\beta_1/\\log_{2}(e)$ which would be interpreted as the multiplicative\nchange in the odds for river-blindness for a doubling in elevation.\nHowever, a doubling in elevation is less meaningful when considering\nlarger values of elevation.\n\n::: callout-note\nThe letter $e$ stands for the so-called Euler's number and represents\nthe base of the natural logarithm. In the book, we write $\\log(\\cdot)$\nto mean the \"natural logarithm of $\\cdot$\".\n:::\n\nWhen the goal of statistical analysis is instead in developing a\npredictive model for the outcome of interest, the explanatory power and\ninterpretability of the model may be of less concern. For this reason,\nthe model with the log-transformed elevation could be preferred over the\nmodel with the linear spline, if it is shown to yield more predictive\npower. We will come back to this point again in @sec-geo-prediction,\nwhere we will show how to assess and compare the predictive performance\nof different geostatistical models.\n\nThe other type of aggregated count data that we consider are unbounded\ncounts. The Anopheles mosquitoes dataset (@sec-mosq-data-ch1) is an\nexample of this, since there is no upper limit to the number of\nmosquitoes that can be trapped at a location. Let us consider the\ncovariate represented by elevation. In this case, the simplest model\nthat can be used to analyse the data is a Poisson regression, where the\nlinear predictor is defined as the log of the mean number of mosquitoes\n(@tbl-glm). Hence, exploratory plots for the association with covariates\nshould be generated using the log transformed counts of mosquitoes. In\nthis instance, to avoid taking the log of zero, we can add 1 to the\nreported counts, if required. The variable `An.gambiae` in the\n`anopheles` dataset does not contain any 0, hence we simply apply the\nlog transformation without adding 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Apply log-transformation to Anopheles gambiaes counts\nanopheles$log_counts <- log(anopheles$An.gambiae)\n\n# Scatterplot of log counts vs. elevation\nggplot(anopheles, aes(x = elevation, y = log_counts)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE) +\n  labs(x = \"Elevation (meters)\", y = \"Log number of An. gambiae mosquitoes\")\n```\n\n::: {.cell-output-display}\n![Scatter plot of the log transformed number of *Anopheles gambiae* mosquitoes against elevation, measured in meters. The blue line is generated using the least squares fit. ](03_model-fitting_files/figure-html/fig-logcounts-elev-mosq-1.png){#fig-logcounts-elev-mosq}\n:::\n:::\n\n\nThe scatter plot in @fig-logcounts-elev-mosq shows a weak negative\nassociation, with the average number of mosquitoes tending to decrease\nas elevation increases. In this case, assuming a linear effect of\nelevation on the log of the expected mosquito count appears reasonable.\n\n#### When the outcome is an individual-level binary indicator {#sec-indiv-expl-analysis}\n\nWe now consider the malaria data from Kenya (@sec-malaria-ch1) where the\nmain outcome is the result from a rapid diagnostic test (RDT) for\nmalaria from individuals within households. In this case, because the\noutcome only takes two values, 1 for a positive RDT test result and 0\notherwise, the direct application of the empirical logit from\n@eq-empirical-logit would not help us to generate informative scatter\nplots. Throughout the book, we will consider the data from the community\nsurvey only, hence we work with a subset of the data which we shall name\n`malkenya_comm`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Subset to community surveys only\nmalkenya_comm <- malkenya[malkenya$Survey == \"community\", ]\n```\n:::\n\n\nTo show how this issue can be overcome, let us consider the variables\nage and gender. To generate a plot that can help us understand between\nthe relationship with malaria prevalence and the two risk factors, we\nproceed as follows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Grouping of ages into classes defined through \"breaks\"\nmalkenya_comm$Age_class <- cut(malkenya_comm$Age,\n  breaks = c(0, 5, 10, 15, 30, 40, 50, 100),\n  include.lowest = TRUE\n)\n```\n:::\n\n\nUsing the `cut()` function, we first split age (in years) into classes\nthrough the argument `breaks`. The classification of age into $[0,5]$,\n$(5, 10]$ and $(10, 15]$ is common in many malaria epidemiology studies.\nFor older ages, there is no strong requirement for a particular\nclassification, and alternative groupings are equally plausible; the\ncategories used here are intended purely for illustration.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Computation of the empirical logit by age class and gender\nage_class_data <- aggregate(RDT ~ Age_class + Gender,\n  data = malkenya_comm,\n  FUN = function(y) elogit(sum(y), length(y))\n)\n```\n:::\n\n\nWe then compute the empirical logit, using the total number of cases\nwithin each combination of age class and gender. For a given age group\nand gender, which we denote as $\\mathcal{C}$, the empirical logit in\n@eq-empirical-logit, now takes the form\n$$\nl_{\\mathcal{C}} = \\log\\left\\{\\frac{\\sum_{i \\in \\mathcal{C}} y_{i} + 0.5}{|\\mathcal{C}|- \\sum_{i \\in \\mathcal{C}} y_{i} + 0.5} \\right\\}\n$$ {#eq-empirical-logit-bin}\nwhere $y_i$ are the individual binary outcomes\nand $i\\in \\mathcal{C}$ is used to indicate that the sum is carried out\nover all the individuals who belong the class $\\mathcal{C}$, identified\nby a specific age group and gender. Finally, $|\\mathcal{C}|$ is the\nnumber of individuals who fall within $\\mathcal{C}$. In the code above,\nthe empirical logit in @eq-empirical-logit-bin is computed using the\n`aggregate()` function. An inspection of the object `age_class_data`, a\ndata frame, shows that the empirical logit is found in the column named\n`RDT`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Computation of the average age by age class and gender\nage_class_data$age_mean_point <- aggregate(Age ~ Age_class + Gender,\n  data = malkenya_comm,\n  FUN = mean\n)$Age\n\n# Number of individuals by age class and gender\nage_class_data$n_obs <- aggregate(Age ~ Age_class + Gender,\n  data = malkenya_comm,\n  FUN = length\n)$Age\n```\n:::\n\n\nIn order to generate the scatter-plot, we compute the average age within\neach age group by gender, and use these as our values for the x-axis.\nNote that since we only need to obtain the average age from this output,\nwe use `$Age` to extract this only and allocate to the column\n`age_mean_point`. Finally, we also compute the number of observations\nwithin each of the groups and place this in `n_obs`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Scatterplot of empirical logit RDT vs. age\nggplot(age_class_data, aes(x = age_mean_point, y = RDT)) +\n  geom_point(aes(size = n_obs, colour = Gender)) +\n  labs(x = \"Age (years)\", y = \"Empirical logit\")\n```\n\n::: {.cell-output-display}\n![Plot of the empirical logit against age, for males and females. The size of each solid point is rendered proportional to the number of individuals within each age and group, as indicated in the legend.](03_model-fitting_files/figure-html/fig-elogit-age-malkenya-1.png){#fig-elogit-age-malkenya}\n:::\n:::\n\n\nThe resulting plot in @fig-elogit-age-malkenya shows the empirical logit\nagainst age by gender, with the size of each of the points proportional\nto the number of observations falling within each class. The observed\npatterns are explained by the fact that young children, especially those\nunder the age of five, are particularly vulnerable to severe malaria\ninfections. This is primarily due to their immature immune systems and\nlack of acquired immunity. As individuals grow older, they generally\ndevelop partial immunity to malaria through repeated exposure to the\ndisease. This acquired immunity can provide some level of protection\nagainst severe malaria. At the same time, gender roles and activities\ncan influence exposure to malaria-carrying mosquitoes. For example, men\nmay spend more time outdoors for work or other activities, increasing\ntheir exposure to mosquito bites and thus their risk of infection. In\naddition, there are also biological factors to consider. Hormonal and\ngenetic differences between males and females may also contribute to\nvariations in immune responses to malaria infection. The interaction\nbetween age and gender is complex and may vary depending on the specific\ncontext and population being studied. A 2020 report from the Bill &\nMelinda Gates foundation provides a detailed overview of this and other\naspects related to gender and malaria [@gates2020].\n\nTo account for age in a model for malaria prevalence, several approaches\nare possible, some of which have been developed using biological models\n[@smith2007]. To model the patterns observed in\n@fig-elogit-age-malkenya, we can follow the same approach used in the\nprevious section to model the relationship between elevation and\nriver-blindness prevalence. First, let us consider age without the\neffect of gender. Let $p_{j}(x_i)$ denote the probability of a positive\nRDT for the $j$-th individual living in a household at location $x_i$.\nAssuming that malaria risk increases during childhood, reaches a peak\naround 15 years of age, and then changes more gradually in adulthood, we\ncan capture this non-linear relationship using a linear spline with two\nknots, at 15 and 40 years. This allows the effect of age to vary across\nthree intervals: childhood, early adulthood, and later adulthood. This\nmodel can be expressed as\n$$\n\\begin{aligned}\n\\log\\left\\{\\frac{p_{j}(x_i)}{1-p_j(x_i)}\\right\\} = \\beta_{0} + \\beta_{1}a_{ij}+\\beta_{2} \\times\\max\\{a_{ij}-15, 0\\} + \\beta_{3}\\max\\{a_{ij}-40, 0\\}\n\\end{aligned}\n$$ {#eq-age-only-reg}\nwhere $a_{ij}$ is the age, in years,\nof the $j$-th individual at household $i$. This formulation defines a\npiecewise linear relationship between age and the log-odds of infection.\nIn particular, the effect of age is $\\beta_{1}$, for $a_{ij} < 15$,\n$\\beta_{1}+\\beta_{2}$, for $15 < a_{ij} < 40$, and\n$\\beta_{1}+\\beta_{2}+\\beta_{3}$ for $a_{ij} > 40$.\n\n@fig-elogit-age-malkenya suggests a potential interaction between age\nand gender, as the difference in RDT prevalence between males and\nfemales appears to vary with age, with wider gaps observed among\nindividuals older than 20 years. To examine this pattern using a\nstandard Binomial regression model, the linear predictor for RDT\nprevalence can be expressed as\n$$\n\\begin{aligned}\n\\log\\left\\{\\frac{p_{j}(x_i)}{1-p_j(x_i)}\\right\\} = \\beta_{0} + (\\beta_{1} + \\beta_{1}^*g_{ij})\\times a_{ij}+(\\beta_{2} + \\beta_{2}^*g_{ij})\\times\\max\\{a_{ij}-15, 0\\} + \\\\\n(\\beta_{3} + \\beta_{3}^*g_{ij}) \\times \\max\\{a_{ij}-40, 0\\}\n\\end{aligned}\n$$ {#eq-age-inter-reg}\nwhere $g_{ij}$ is the indicator for\ngender, with 1 corresponding to male and 0 to female. The coefficients\n$\\beta_{1}^*$, $\\beta_{2}^*$ and $\\beta_{3}^*$ thus quantify the\ndifferences in risk between the two genders for ages below 15 years,\nbetween 15 and 40 years, and above 40 years, respectively. If all of\nthose coefficients were 0, the model in @eq-age-only-reg would be\nrecovered.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit binomial model with age (piecewise linear) and gender interaction\nglm_age_gender_interaction <- glm(\n  RDT ~ Age + Gender:Age +\n    pmax(Age - 15, 0) + Gender:pmax(Age - 15, 0) +\n    pmax(Age - 40, 0) + Gender:pmax(Age - 40, 0),\n  data = malkenya_comm, family = binomial\n)\n```\n:::\n\n\nThe code above shows how to fit the model specified in\n@eq-age-inter-reg. The terms `Age`, `pmax(Age-15, 0)` and\n`pmax(Age-40, 0)` respectively correspond to $\\beta_{1}$, $\\beta_{2}$\nand $\\beta_{3}$, whilst the `Gender:Age`, `Gender:pmax(Age-15, 0)` and\n`Gender:pmax(Age-40, 0)` to $\\beta_{1}^*$, $\\beta_{2}^*$ and\n$\\beta_{3}^*$, respectively.\n\n\n::: {#tbl-age-gender-interaction .cell tbl-cap='Estimated coefficients for the age-by-sex interaction model.'}\n::: {.cell-output-display}\n\n\n|Parameter   |Term                      | Estimate| Std. error| z value| p-value|\n|:-----------|:-------------------------|--------:|----------:|-------:|-------:|\n|$\\beta_0$   |Intercept                 |   -1.058|      0.102| -10.331|   0.000|\n|$\\beta_1$   |Age                       |   -0.034|      0.013|  -2.584|   0.010|\n|$\\beta_2$   |Age above 15 years        |   -0.040|      0.024|  -1.687|   0.092|\n|$\\beta_3$   |Age above 40 years        |    0.092|      0.025|   3.695|   0.000|\n|$\\beta_1^*$ |Male × age                |    0.014|      0.012|   1.170|   0.242|\n|$\\beta_2^*$ |Male × age above 15 years |   -0.036|      0.031|  -1.153|   0.249|\n|$\\beta_3^*$ |Male × age above 40 years |    0.025|      0.043|   0.567|   0.571|\n\n\n:::\n:::\n\n\nThe estimated coefficients are reported in @tbl-age-gender-interaction.\nThe three interaction coefficients are not individually statistically\nsignificant at the 5% level. However, removing the interaction on the\nbasis of these individual p-values would be inappropriate, because the\ninteraction is represented by three coefficients. Instead, the model\nwith and without the interaction terms should be compared using a\nlikelihood ratio test, as shown below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit binomial model with age (piecewise linear)\nglm_age_gender_no_interaction <- glm(\n  RDT ~ Age +\n    pmax(Age - 15, 0) +\n    pmax(Age - 40, 0),\n  data = malkenya_comm, family = binomial\n)\n\n# Perform likelihood ration test\nanova(glm_age_gender_no_interaction, glm_age_gender_interaction, test = \"Chisq\")\n```\n:::\n\n\n\n::: {#tbl-lrt-age-gender .cell tbl-cap='Likelihood ratio test comparing models with and without age-by-sex interactions.'}\n::: {.cell-output-display}\n\n\n|Model                              | Residual df| Residual deviance|Difference in deviance |p-value |\n|:----------------------------------|-----------:|-----------------:|:----------------------|:-------|\n|Reduced model (no interaction)     |        3348|           2675.62|                       |        |\n|Full model (age × sex interaction) |        3345|           2673.82|1.81                   |0.61    |\n\n\n:::\n:::\n\n\nTo assess the null hypothesis that\n$\\beta_{1}^*=\\beta_{2}^*=\\beta_{3}^*=0$, we compare the model with and\nwithout the age-by-sex interaction terms. This is done by fitting the\nreduced model under the null hypothesis and performing a likelihood\nratio test using the `anova()` function. The results are reported in\n@tbl-lrt-age-gender. The p-value indicates that we do not find evidence\nagainst the null hypothesis, hence in our analysis of the data we might\nfavour the simplified model that does not assume an interaction between\nthe two genders. However, it is important to note that the likelihood\nused here comes from a standard Binomial model that does not account for\nresidual spatial correlation. As will be shown later in the book,\nignoring such correlation typically leads to underestimated standard\nerrors for the regression coefficients and, consequently, p-values that\nare smaller than they should be. The resulting p-values from the\nlikelihood ratio test may therefore be unreliable. Nonetheless, these\nexploratory analyses remain useful for identifying patterns that may or\nmay not persist once a more flexible model is fitted. In practice, if an\ninteraction appears weak or non-significant at this stage, one would\nexpect even less evidence for it under a model that captures additional\nvariability. Conversely, when certain relationships are scientifically\nplausible - such as age-specific differences between genders - it may\nstill be appropriate to retain them regardless of their statistical\nsignificance.\n\nThe approach just illustrated, can also be applied to explore the\nassociation with other continuous variables that are a property of the\nhousehold and not of the individual. Let us, for example, consider the\nvariable `elevation` from the `malkenya` dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Split elevation into classes by deciles\nmalkenya_comm$elevation_class <- cut(malkenya_comm$elevation,\n  breaks = quantile(\n    malkenya_comm$elevation,\n    seq(0, 1, by = 0.1)\n  ),\n  include.lowest = TRUE\n)\n```\n:::\n\n\nFollowing the same approach used for age, we first split elevation into\nclasses. To define these, we use the deciles of the empirical\ndistribution of `elevation` which we calculate using the `quantile()`\nfunction above. In this way we also ensure that the number of\nobservations falling within each class of elevation is approximately the\nsame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Computation of the empirical logit by classes of elevation\nelev_class_data <- aggregate(RDT ~ elevation_class,\n  data = malkenya_comm,\n  FUN = function(y) elogit(sum(y), length(y))\n)\n\n# Computation of the average elevation within each class of elevation\nelev_class_data$elevation_mean <- aggregate(elevation ~ elevation_class,\n  data = malkenya_comm,\n  FUN = mean\n)$elevation\n\n# Computation of the number of observations within each class of elevation\nelev_class_data$n_obs <- aggregate(elevation ~ elevation_class,\n  data = malkenya_comm,\n  FUN = length\n)$elevation\n```\n:::\n\n\nWe then compute the empirical logit, the average elevation and total\nnumber of observations for each class of elevation. The empirical logit\nis computed as already defined in @eq-empirical-logit-bin, where now the\ndefinition of $\\mathcal{C}$ is given by a specific decile used to split\nthe distribution of elevation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Scatterplot of the empirical logit of RDT vs. mean elevation\nggplot(elev_class_data, aes(x = elevation_mean, y = RDT)) +\n  geom_point(aes(size = n_obs)) +\n  labs(x = \"Elevation (meters)\", y = \"Empirical logit\")\n```\n\n::: {.cell-output-display}\n![Plot of the empirical logit against elevation measured in meters.](03_model-fitting_files/figure-html/fig-elogit-elev-malkenya-1.png){#fig-elogit-elev-malkenya}\n:::\n:::\n\n\nThe resulting plot in @fig-elogit-elev-malkenya shows an approximately\nlinear relationship with decreasing values of the empirical logit for\nincreasing elevation. This is expected because the cooler environment at\nhigher altitudes is less favourable to the development of the overall\nmosquito life cycle.\n\nAn alternative approach to generate a scatter plot for assessing the\nassociation between elevation and the empirical logit would be to\naggregate the data at household level, rather than using classes of\nelevation. However, this approach cannot be applied when only one\nindividual is sampled for each household. In the case of the `malkenya`\ndata, the great majority of the households only include one individual\nmaking this second approach less useful than the one illustrated.\n\nOther more sophisticated approaches for the exploration of the\nassociations between covariates and binary outcomes are available. For\nexample, the use of the empirical logit could be avoided by using\nnon-parametric regression methods for Binomial outcomes [@bowman1997],\nalso implemented in the sm package in R. Our view is that a careful\nexploratory analysis based on simpler methods, such as those illustrated\nabove, can be equally effective to inform the model formulation.\n\n### Exploring overdispersion in count data {#sec-overdispersion}\n\nOne of the main advantages in the use of covariates is the ability to\nattribute part of the variation in the outcome to a set of measured\nvariables and, hence, reduce the uncertainty of our inferences. However,\nit is almost always the case that the finite number of covariates at our\ndisposal is not enough to fully explain the variation in the outcome.\nThe existence of unmeasured covariates that are related to the modelled\noutcome gives rise to the so-called residual variation. In a standard\nlinear regression model the extent to which we are able to account for\nimportant covariates is directly linked to the size of the variance of\nthe residuals. In the case of count data, instead, this link is less\nwell defined and one of the main consequences of the omission of\ncovariates, which we address in this chapter, is *overdispersion*.\n\nOverdispersion occurs when the variability of the data is larger than\nthat implied by the generalized linear model (GLM) fitted to them. For\nexample, if we consider the Binomial distribution, the presence of\noverdispersion implies that $V(Y_i) > m_i \\mu_{i}(1-\\mu_i)$, where we\nrecall that $m_i$ is the Binomial denominator and $\\mu_i$ is the\nprobability of \"success\" for each of the $m_i$ Bernoulli trials; for a\nPoisson distribution with $E(Y_i) = \\mu_i$, instead, overdispersion\nimplies that $V(Y_i) > \\mu_{i}$.\n\nAssessment of the overdispersion for count data can be carried out in\ndifferent ways depending on the goal of the statistical analysis. Since\nthe focus of this book is to illustrate how to formulate and apply\ngeostatistical models, the most natural approach to assess\noverdispersion is through the use of generalized linear mixed models\n(GLMMs). The class of GLMMs that we consider in this and the next\nsection are obtained by replacing the spatial Gaussian process $S(x_i)$\nin introduced in @eq-linear-predictor-ch1 with a set of mutually\nindependent random effects, which we denote as $Z_i$, and thus write\n$$\ng(\\mu_i) = d(x_i)^\\top \\beta + Z_i.\n$$ {#eq-linear-predictor-glmms-ch2}\nThe model above accounts for the overdispersion in the data through\n$Z_i$ whose variance can be interpreted as an indicator of the amount of\noverdispersion. To show this, we carry out a small simulation as\nfollows. For simplicity, we consider the Binomial mixed model with an\nintercept only, hence\n$$\n\\log\\left\\{\\frac{\\mu_i}{1-\\mu_i}\\right\\} = \\beta_0 + Z_i\n$$ {#eq-bin-glmm-example}\nand assume that the $Z_i$ follow a set of\nmutually independent Gaussian variables with mean 0 and variance\n$\\tau^2$. In our simulation we vary $\\beta_0$ over the set\n$\\{-3, -2, -1, 0, 1, 2, 3\\}$ and set $\\tau^2=0.1$ and the binomial\ndenominators to $n_i = 100$. For a given value of $\\beta_0$, we then\nproceed through the following iterative steps.\n\n-   Simulate 10,000 values for $Z_i$ from a Gaussian distribution with\n    mean 0 and variance $\\tau^2$.\n\n-   Compute the probabilities $\\mu_i$ based on @eq-bin-glmm-example.\n\n-   Simulate 10,000 values from a Binomial model with probability of\n    success $\\mu_i$ and denominator $n_i$.\n\n-   Compute the empirical variance of the counts $y_i$ simulated in the\n    previous step.\n\n-   Change the value of $\\beta_0$ and repeat the previous steps, for all\n    the values of $\\beta_0$.\n\nThe code below shows the implementation of the above steps in R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number of simulations\nn_sim <- 10000\n\n# Variance of the Z_i\ntau2 <- 0.1\n\n# Binomial denominator\nbin_denom <- 100\n\n# Intercept values\nbeta0 <- c(-3, -2, -1, 0, 1, 2, 3)\n\n# Vector where we store the computed variance from\n# the simulated counts from the Binomial mixed model\nvar_data <- rep(NA, length(beta0))\n\n\nfor (j in 1:length(beta0)) {\n\n  # Simulation of the random effects Z_i\n  Z_i_sim <- rnorm(n_sim, sd = sqrt(tau2))\n\n  # Linear predictor of the Binomial mixed model\n  lp <- beta0[j] + Z_i_sim\n\n  # Probabilities of the Binomial distribution conditional on Z_i\n  prob_sim <- exp(lp) / (1 + exp(lp))\n\n  # Simulation of the counts from the Binomial mixed model\n  y_i_sim <- rbinom(n_sim, size = bin_denom, prob = prob_sim)\n\n  # Empirical variance from the simulated counts\n  var_data[j] <- var(y_i_sim)\n}\n\n# Probabilities from the standard Binomial model (Z_i = 0)\nprobs_binomial <- exp(beta0) / (1 + exp(beta0))\n\n# Variance from the standard Binomial model\nvar_binomial <- bin_denom * probs_binomial * (1 - probs_binomial)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a data.frame for plotting the results\nplot_df <- data.frame(\n  beta0 = beta0,\n  Binomial.mixed.model = var_data,\n  Standard.Binomial.model = var_binomial\n) |>\n  pivot_longer(\n    cols = c(Binomial.mixed.model, Standard.Binomial.model),\n    names_to = \"Model\",\n    values_to = \"Variance\"\n  ) |>\n  mutate(Model = factor(Model,\n    levels = c(\n      \"Binomial.mixed.model\",\n      \"Standard.Binomial.model\"\n    ),\n    labels = c(\n      \"Binomial mixed model\",\n      \"Standard Binomial model\"\n    )\n  ))\n\nggplot(plot_df, aes(x = beta0, y = Variance, color = Model)) +\n  geom_point() +\n  geom_line() +\n  labs(x = expression(beta[0]), y = \"Variance\") +\n  scale_color_brewer(type = \"q\", palette = 2) +\n  theme_minimal() +\n  theme(legend.title = element_blank(), legend.position = c(0.2, 0.85))\n```\n\n::: {.cell-output-display}\n![Plot of the variances of the standard Binomial model and the Binomial mixed model (see @eq-bin-glmm-example) against  $\\beta_0$](03_model-fitting_files/figure-html/fig-var-bin-glmm-1.png){#fig-var-bin-glmm}\n:::\n:::\n\n\n@fig-var-bin-glmm shows the results of the simulation. In this figure,\nthe orange line corresponds to the variance of a standard Binomial\nmodel, obtained by setting $Z_i=0$ and computed as $n_i \\mu_i (1-\\mu_i)$\nwith $\\mu_i = \\exp\\{\\beta_0\\}/(1+\\exp\\{\\beta_0\\})$. As expected, this\nplot shows that the variance of the simulated counts from the mixed\nmodel in @eq-bin-glmm-example exhibit a larger variance than would be\nexpected under the standard Binomial model. It also indicates that the\nchosen value for the variance of $Z_i$ of $\\tau^2 = 0.1$ corresponds to\na significant amount of dispersion. One way to relate $\\tau^2$ to the\namount of overdispersion is by considering that, following from the\nproperties of a univariate Gaussian distribution, *a priori* the $Z_i$\nwill take values between $-1.96 \\sqrt{\\tau^2}$ and $+1.96 \\sqrt{\\tau^2}$\nwith approximately 95$\\%$ probability. That implies that $\\exp\\{Z_i\\}$,\nwhich expresses the effect of the random effects on the odds ratios,\nwill be with 95$\\%$ probability between $\\exp\\{-1.96 \\sqrt{\\tau^2}\\}$\nand $\\exp\\{+1.96 \\sqrt{\\tau^2}\\}$. By replacing $\\tau^2$ with the chosen\nvalues for the simulation, those two become about 0.54 and 1.86, meaning\nthat with the $Z_i$ with $95\\%$ probability will have a multiplicative\neffect on the odds ratios between $0.54$ and $1.86$.\n\nTo consolidate the concepts introduced so far, we encourage you to\ncomplete Exercises 1 and 2 at the end of this chapter, which further\nexplore the use of generalized linear mixed models as a tool for\naccounting for overdispersion.\n\n#### Maximum likelihood estimation of generalized linear mixed models for count data\n\nWe now illustrate how to fit a generalized linear mixed, using the\n`anopheles` dataset as an example. We consider two models: an\nintercept-only model and one that uses elevation as a covariate. Let\n$\\mu(x_i)$ be the number of mosquitoes captured at a location $x_i$;\nthen the linear predictor with elevation as a covariate takes the form\n$$\n\\log\\{\\mu_i\\} = \\beta_{0} + \\beta_{1} d(x_i) + Z_i\n$$ {#eq-anopheles-glmm}\nwhere $d(x_i)$ indicates the elevation in meters at\nlocation $x_i$ and the $Z_i$ are independent and identically distributed\nGaussian variables with mean 0 and variance $\\tau^2$. The model with an\nintercept only is simply obtained by setting $\\beta_1 = 0$.\n\nWe carry out the estimation in R using the `glmer()` function from the\nlme4 package (see @bates2015 for a detailed tutorial). The `glmer()`\nfunction implements the maximum likelihood estimation for generalized\nlinear mixed models. The code below shows how `glmer()` is used to carry\nout this step for the model in @eq-anopheles-glmm and the one without\ncovariates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create an ID for the location\nanopheles$ID_loc <- 1:nrow(anopheles)\n\n# Poisson mixed model with elevation\nfit_glmer_elev <- glmer(An.gambiae ~ scale(elevation) + (1 | ID_loc),\n  family = poisson, data = anopheles, nAGQ = 25\n)\n\n# Poisson mixed model with intercept only\nfit_glmer_int <- glmer(An.gambiae ~ (1 | ID_loc),\n  family = poisson, data = anopheles, nAGQ = 25\n)\n```\n:::\n\n\nTo fit the model with `glmer()`, we first must create a variable in our\ndataset that allows us to identify the location associated with each\ncount. In this case, since every row corresponds to a different\nlocation, we simply use the row number to identify the locations and\nsave this in a new column called `ID_loc`. The random effects $Z_i$ are\nthen included in the model by adding `(1 | ID_loc)` in the formula of\nthe `glmer()` function.\n\nWhen introducing the variable elevation, we standardize it so that its\nmean is 0 and its variance is 1. This helps the model-fitting algorithm\nconverge more reliably and is generally good practice when covariates\nare measured on very different scales. Importantly, standardizing a\nvariable does not change the fit of the model to the data, it only\nchanges how we interpret the regression coefficients. In other words,\nthe model is mathematically equivalent; only the units of measurement\ndiffer. For example, suppose we model mosquito counts using elevation\nmeasured in metres and obtain a regression coefficient of –0.002. Under\nour log-link model, this implies that a one-metre increase in elevation\nmultiplies the expected mosquito count by $\\exp(-0.002) \\approx0.998$,\ncorresponding to an approximate decrease of\n$100\\%\\times{\\exp(−0.002)−1}\\approx−0.2\\%$. If we instead standardize\nelevation so that one unit represents one standard deviation (say 150\nm), the corresponding coefficient becomes –0.002 × 150 = –0.30. Both\nmodels yield identical fitted values and predictions. The only\ndifference is that in the standardized model, the coefficient refers to\na one-standard-deviation change in elevation rather than a one-metre\nchange. Standardization also changes the interpretation of the\nintercept. In the unstandardized model, the intercept corresponds to the\nexpected response when elevation is 0 m, whereas in the standardized\nmodel it corresponds to the expected response at the mean elevation.\nSince the latter is often more meaningful, standardization can also\nimprove the interpretability of the intercept.\n\nThe argument `nAGQ` is used to define the precision of the approximation\nof the maximum likelihood estimation algorithm. By default `nAGQ = 1`,\nwhich corresponds to the Laplace approximation. Values for `nAGQ` larger\nthan 1 are used to define the number of points of the adaptive\nGaussian-Hermite quadrature. The general principle is that the larger\n`nAGQ` the better, but at the expense of an increased computing time.\nBased on the guidelines and help pages of the lme4 package, it is stated\nthat a reasonable value for `nAGQ` is 25. For more technical details on\nthis aspect, we refer you to @bates2015.\n\nWe can now summarise the fitted models for the mosquito dataset by\nreporting the quantities that are most relevant for interpretation,\nrather than printing the full output returned by `summary()`.\n\n\n::: {#tbl-glmer-elevation-coef .cell tbl-cap='Estimated fixed effects for the model including elevation.'}\n::: {.cell-output-display}\n\n\n|Term                     | Estimate| Std. error| z value| p-value| Exponentiated estimate|Interpretation                            |\n|:------------------------|--------:|----------:|-------:|-------:|----------------------:|:-----------------------------------------|\n|Intercept                |    1.530|      0.094|  16.342|   0.000|                   4.62|Expected mosquito count at mean elevation |\n|Elevation (standardised) |   -0.198|      0.089|  -2.212|   0.027|                   0.82|Multiplicative change per 1 SD increase   |\n\n\n:::\n:::\n\n\n\n::: {#tbl-glmer-fit-comparison .cell tbl-cap='Comparison of the intercept-only model and the model including elevation.'}\n::: {.cell-output-display}\n\n\n|Model          |     AIC|     BIC| Log-likelihood| Random-effect variance| Random-effect SD|\n|:--------------|-------:|-------:|--------------:|----------------------:|----------------:|\n|Intercept only | 294.599| 300.106|       -145.300|                  0.761|            0.872|\n|Elevation      | 291.838| 300.098|       -142.919|                  0.715|            0.845|\n\n\n:::\n:::\n\n\nThe estimated fixed effects for the model including elevation are\nreported in @tbl-glmer-elevation-coef. The estimated regression\ncoefficient associated with elevation, $\\beta_1$, is negative and\nstatistically significant, suggesting that mosquito abundance decreases\nas elevation increases. Since the model uses a logarithmic link\nfunction, exponentiating the coefficient gives the multiplicative effect\non the expected mosquito count. In this case, a one-standard-deviation\nincrease in elevation multiplies the expected mosquito count by\n$\\exp(-0.19794)=0.82$, corresponding to an approximate reduction of\n$$\n100 \\times \\{\\exp(-0.19794)-1\\} \\approx -18\\%.\n$$\n\nBecause elevation has been standardised, a one-unit increase corresponds\nto an increase in the original elevation variable equal to its standard\ndeviation, which for the `elevation` variable is approximately 100\nmetres.\n\nThe exponentiated intercept reported in @tbl-glmer-elevation-coef also\nhas a useful interpretation. Since elevation has been standardised to\nhave mean 0, the intercept corresponds to the expected mosquito count at\nthe mean elevation, for a location whose random effect is equal to zero.\n\nThe comparison between the intercept-only model and the model including\nelevation is shown in @tbl-glmer-fit-comparison. From this table, we\nobserve that the estimated variance of the random effect, $\\tau^2$,\ndecreases slightly from 0.761 in the intercept-only model to 0.715 in\nthe model including elevation. Recall that $\\tau^2$ represents the\nvariance of the location-specific random effects $Z_i$. The quantities\nreported under `Random-effect SD` are simply the square roots of the\ncorresponding variances.\n\nAs expected, including elevation in the model explains a small\nproportion of the between-location variability captured by the random\neffects, though a substantial amount of residual variation remains\nunexplained. The estimated values of $\\tau^2$ therefore suggest the\npresence of extra-Poisson variation in the mosquito counts that is not\naccounted for by elevation alone.\n\nIn the next section, we will illustrate how to assess the presence of\nresidual correlation for continuous measurements and overdispersed count\ndata.\n\n### Exploring residual spatial correlation {#sec-expl-spatial}\n\nIn its most basic form, the concept of spatial correlation can be\nsuccinctly encapsulated by @tobler1970 first law of geography, which\nposits that \"everything is interconnected, but objects in close\nproximity exhibit stronger relationships than those situated farther\napart.\" After we have identified the key variables to introduce as\ncovariates in the model (@sec-expl-assoc) and, in the case of count\ndata, assessed the presence of overdispersion (@sec-overdispersion), our\nfinal exploratory step consists of assessing whether the residuals of\nthe non spatial model show evidence of spatial correlation. Hence, in\ngeostatistical modelling, the interest is not in the spatial correlation\nof the data, but rather in understanding whether the variation in the\noutcome unexplained by the covariates exhibits spatial correlation. We\ncall this *residual spatial correlation*, to emphasize that spatial\ncorrelation is a concept relative to the covariates that we have\nintroduced in the model.\n\nIn the context of geostatistical analysis, the tool that is generally\nused to assess the residual spatial correlation is the so-called\n*empirical variogram*. Before looking at the mathematical definition of\nthe empirical variogram, let us consider a generalized linear mixed\nmodel as expressed in @eq-linear-predictor-glmms-ch2. Our goal is then\nto question the assumption of independently distributed random effects\n$Z_i$ by asking whether the $Z_i$ show evidence of spatial correlation.\nLet $Z_i$ and $Z_j$ be two random effects that are associated with two\ndifferent locations $x_i$ and $x_j$, respectively, and let us take the\nsquared difference between the two\n$$\nV_{ij} = (Z_i - Z_j)^2.\n$$ {#eq-squared-diff}\nHow does the spatial\ncorrelation affect the value of $V_{ij}$? To answer this question, we\ncan refer to the aforementioned Tobler's law of geography. When $x_i$\nand $x_j$ will be closer to each other, then $Z_i$ and $Z_j$ will also\ntend to be more similar to each other, thus making $V_{ij}$ smaller, on\naverage. On the contrary, when $x_i$ and $x_j$ will be further apart,\nthen $V_{ij}$ will become larger, on average. We can then construct the\nempirical variogram by considering all possible pairs of locations $x_i$\nand $x_j$, for which we then compute $V_{ij}$ and plot this against the\ndistance between $x_i$ and $x_j$, which we denote as $u_{ij}$. If there\nis spatial correlation in the random effects $Z_i$, then this will\nmanifest as an average increase in the $V_{ij}$ as $u_{ij}$ increases.\nHowever, there are still two issues that we have to address before we\ncan generate and plot the empirical variogram.\n\nThe first issue is that we do not observe $Z_i$ as, by definition, this\nis a latent variable. Hence, we require an estimate for $Z_i$ which we\ncan then feed into $V_{ij}$. To emphasize this point, from now on, we\nshall replace @eq-squared-diff with\n$$\n\\hat{V}{ij} = (\\hat{Z}{i} - \\hat{Z}_j)^2.\n$$ {#eq-hat-squared-diff}\nSeveral options are available for estimating $Z_{i}$. Our choice is to\nuse the model of the predictive distribution of $Z_i$, that is the\ndistribution of $Z_{i}$ conditioned to the data $y_i$. This estimator\nfor $Z_i$ is also readily available from the output of the `lmer()` and\n`glmer()` functions of the lme4 package, as we will illustrate later in\nour example in this section.\n\nThe second issue is that if we simply plot $\\hat{V}_{ij}$ against the\ndistances $u_{ij}$ (also known as *cloud variogram*; see Exercise 3 at\nthe bottom of this chapter), due to the high noisiness in the\n$\\hat{V}_{ij}$, it may be quite difficult to assess the presence of an\nincreasing trend in the $\\hat{V}_{ij}$ and thus detect spatial\ncorrelation. Hence, it is general practice to group the distances\n$u_{ij}$ into classes, say $\\mathcal{U}$, and then take average of all\nthe $\\hat{V}_{ij}$ that fall within $\\mathcal{U}$. We can now write the\nformal definition of the empirical variogram as\n$$\n\\hat{V}(\\mathcal{U}) = \\frac{1}{2 |\\mathcal{U}|} \\sum_{(i, j): (u_i,\nu_j) \\in \\mathcal{U}} \\hat{V}{ij}\n$$ {#eq-empirical-variogram}\nwhere\n$|\\mathcal{U}|$ denotes the number of pairs of locations that fall\nwithin the distance class $\\mathcal{U}$. The rationale behind dividing\nby 2 in $1/2 |\\mathcal{U}|$ from the above equation, will be elucidated\nin @sec-linear-model. When creating the empirical variogram plot, we\nselect the midpoint values of the distance classes $\\mathcal{U}$ to\nrepresent the x-axis values.\n\nBefore we can evaluate residual spatial correlation, there remains one\ncrucial concern: relying solely on a visual inspection of the empirical\nvariogram is susceptible to human subjectivity. Furthermore, it is worth\nnoting that even a seemingly upward trend observed in the empirical\nvariogram might be merely a product of random fluctuations, rather than\na reliable indication of actual residual spatial correlation. To address\nthese concerns and enhance the objectivity of the use of the empirical\nvariogram, one approach would involve comparing the observed empirical\nvariogram pattern with those generated in the absence of spatial\ncorrelation. Following this principle, we then use a permutation test\nthat allows us to generate empirical variograms under the assumption of\nabsence of spatial correlation through the following iterative steps.\n\n1.  Permute the order of the locations in the dataset while keeping\n    everything else fixed.\n\n2.  Compute the empirical variogram $\\hat{V}(\\mathcal{U})$ for the\n    permuted dataset.\n\n3.  Repeat 1 and 2 a large number of times, say 10,000.\n\n4.  Use the resulting 10,000 empirical variograms to compute 95$\\%$\n    confidence intervals, by taking the 0.025 and 0.975 quantiles of\n    these for each distance class $\\hat{V}(\\mathcal{U})$.\n\n5.  If the observed empirical variogram lies entirely within the\n    envelope generated in the previous step, we conclude that there is\n    no evidence of residual spatial correlation in the data. When,\n    instead, parts of the empirical variogram fall outside the envelope,\n    this suggests the presence of residual spatial dependence.\n\nIn point 5 above, the extent and pattern of these deviations can vary\nconsiderably. In many cases, the departures from the envelope are quite\nsubtle, with only a few points of the empirical variogram falling\noutside, as we will see in later examples. Such patterns may indicate\nweak spatial dependence that is difficult to recover from the data.\n\nUltimately, only the fit of a geostatistical model can provide a\ndefinitive assessment of the extent of the spatial correlation. The\nempirical variogram should therefore be viewed as a diagnostic tool that\nhelps to explore residual spatial correlation, rather than as conclusive\nevidence on its own.\n\nWe now show an application of all the concepts introduced in this\nsection to the Liberia data on river-blindness.\n\n#### Example: assessing spatial correlation for the Liberia data {#sec-empirical-variog-bin}\n\nWe consider the Binomial mixed model that uses the log-transformed\nelevation as a covariate to model river blindness prevalence, hence\n$$\n\\log\\left\\{\\frac{p(x_i)}{1-p(x_i)}\\right\\} = \\beta_{0} + \\beta_{1}\\log\\{d(x_i)\\} + Z_i\n$$ {#eq-liberia-bin-mixed-elev}\nwhere $d(x_i)$ is the elevation in\nmeters at location $x_i$ and the $Z_i$ are i.i.d. Gaussian variables\nwith mean 0 and variance $\\tau^2$. We first fit the model above using\nthe `glmer()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert the dataset into an sf object\nliberia <- st_as_sf(liberia, coords = c(\"long\", \"lat\"), crs = 4326)\n\n# Create the ID of the location\nliberia$ID_loc <- 1:nrow(liberia)\n\n# Binomial mixed model with log-elevation\nfit_glmer_lib <- glmer(cbind(npos, ntest - npos) ~ log(elevation) + (1 | ID_loc),\n  family = binomial, data = liberia, nAGQ = 25\n)\n```\n:::\n\n\n\n::: {#tbl-glmer-liberia .cell tbl-cap='Estimated parameters for the Liberia binomial mixed model.'}\n::: {.cell-output-display}\n\n\n|Parameter |Term                                  | Estimate| Std. error| z value| p-value|\n|:---------|:-------------------------------------|--------:|----------:|-------:|-------:|\n|$\\beta_0$ |Intercept                             |   -3.122|      0.264| -11.847|       0|\n|$\\beta_1$ |Log elevation                         |    0.332|      0.051|   6.463|       0|\n|$\\tau^2$  |Location-level random-effect variance |    0.085|           |        |        |\n\n\n:::\n:::\n\n\nThe parameter estimates are reported in @tbl-glmer-liberia. The estimate\nof $\\tau^2$ quantifies the residual variation between locations after\naccounting for elevation and represents a moderate level of overdispersion.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nliberia$Z_hat <- ranef(fit_glmer_lib)$ID_loc[, 1]\n```\n:::\n\n\nThrough the function `ranef()` when extracting the estimates of the random\neffects $Z_i$ and save these in the data set. We then use the function\n`variogram()` from the RiskMap package to compute the empirical\nvariogram for the estimated $\\hat{Z}_i$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nliberia_variog <- variogram(\n  data = liberia,\n  variable = \"Z_hat\",\n  breaks = c(\n    15, 30, 40, 80, 120,\n    160, 200, 250, 300, 350\n  ),\n  scale_to_km = TRUE,\n  n_permutations = 1000\n)\n```\n:::\n\n\nThrough the argument `breaks` we can specify the classes of distance,\npreviously denoted by $\\mathcal{U}$; check the help page of\n`variogram()` to see how this is defined by default. The values passed\nto `breaks` in the code above correspond to define the following classes\nof distance $\\mathcal{U}$: $[15, 30]$, $(30, 40]$ and so forth, with the\nlast class being $[350, +\\infty)$, i.e. all pairs of locations whose\ndistances are above 350km. The argument `n_permutations` allows the user\nto specify the number of permutations that are performed to generate the\nenvelope for absence of spatial correlation, previously described.\n\n::: {.cell}\n\n```{.r .cell-code}\ndist_summaries(data = liberia, scale_to_km = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$min\n[1] 3.223757\n\n$max\n[1] 516.3997\n\n$mean\n[1] 200.1551\n\n$median\n[1] 186.06\n```\n\n\n:::\n:::\n\n\nThe `dist_summaries()` function within the RiskMap package can be used\nfor gauging the extent of the area covered by your dataset, aiding in\nthe selection of appropriate values to be passed to the `breaks` argument.\n\nIn the provided output above, we observe that for the Liberia dataset,\nthe minimum and maximum distances are approximately 3km and 533km,\nrespectively. While there is not a one-size-fits-all recommendation for\nsetting `breaks`, two fundamental principles should inform your choice.\nFirstly, it is advisable to avoid choosing overly large distance\nintervals, as the uncertainty associated with the empirical variogram\ntends to increase with distance due to fewer available pairs of\nobservations for estimation. Secondly, especially when spatial\ncorrelation is not strong, it is crucial to carefully explore the\nbehavior of the variogram at smaller distances. Consequently, it is\ngenerally advisable to experiment with different `breaks` configurations\nand observe how they impact the pattern of the empirical variogram.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_variogram(liberia_variog, plot_envelope = TRUE)\n```\n\n::: {.cell-output-display}\n![Plot of the empirical variogram (solid line) computed using the estimated random effects from the model in @eq-liberia-bin-mixed-elev. The blue shaded area is the 95% confidence level envelope generated using the permutation procedure described in @sec-expl-spatial.](03_model-fitting_files/figure-html/fig-liberia-variog-1.png){#fig-liberia-variog}\n:::\n:::\n\n\nFinally, the `plot_variogram()` function enables us to visualize the\nempirical variogram and, through the `plot_envelope()` argument, include\nthe envelope generated by the permutation procedure. As illustrated in\n@fig-liberia-variog, we observe that the empirical variogram falls\noutside the envelope at relatively short distances, typically below\n30km. However, for distances exceeding 30km, the behavior of the\nempirical variogram does not significantly differ from variograms\ngenerated under the assumption of spatial independence. In summary, we\ninterpret the evidence presented in @fig-liberia-variog as indicative of\nresidual spatial correlation within the data. Nevertheless, it is\nessential to exercise caution when attempting to ascertain the scale of\nthe spatial correlation using the empirical variogram. As we will\nemphasize throughout this book, the empirical variogram's sensitivity to\nthe choice of breaks values renders it an unreliable tool for drawing\nstatistical inferences. In other words, we recommend employing the\nempirical variogram primarily to assess the presence of residual\ncorrelation.\n\n#### Exploring residual spatial correlation with linear Gaussian models {#sec-empirical-variog-lm}\n\nWhen using a linear model to assess spatial correlation, it is important\nto distinguish two cases: 1) when the data contain only one observation per\nlocation; 2) when more than one observation per location is available.\nWe now consider each of these two scenarios separately.\n\n##### One observation per location\n\nTo illustrate the use of the variogram in this context, we consider the\nGalicia data on lead concentration in moss samples. Let $L_i$ denote the\nobserved lead concentration at location $x_i$. Because lead\nconcentrations are positive and their distribution is right-skewed, we\nanalyse them on the logarithmic scale and define\n$Y_i = \\log(L_i)$. The logarithmic transformation reduces the influence\nof unusually large observations, helps to stabilise the variance, and\nmakes the Gaussian modelling assumption more plausible. The simplest\npossible model for $Y_i$ is a standard linear model without covariates,\nwhich assumes independence among observations:\n\n$$\nY_i = \\beta_0 + U_i,\n$$ {#eq-std-lm-galicia}\n\nwhere the $U_i$ are independent Gaussian random variables with mean zero\nand variance $\\omega^2$. Our goal at this stage is to assess whether this\nassumption of independence is supported by the data, or whether there is\nevidence of spatial correlation.\n\nHowever, measurement error from the sampling device may contribute to\nthe observed variability in $Y_i$. If such error is large relative to\nthe underlying spatial variation, it can obscure the detection of\nspatial correlation in the residuals. One might therefore consider\nintroducing an additional, location-specific random effect, say $Z_i$,\nwith mean zero and variance $\\tau^2$, leading to the model\n\n$$\nY_i = \\beta_0 + Z_i + U_i,\n$$ {#eq-std-lm2-galicia}\n\nwhere $Z_i$ represents spatially structured variation due to unmeasured\ncovariates, and $U_i$ represents unstructured variation, such as\nmeasurement error. However, this model is not identifiable because the\ntwo random effects, $Z_i$ and $U_i$, both contribute additively to the\ntotal variance, making it impossible to separate their effects unless\none of two conditions is met:\n\n(a) the measurement error variance $\\omega^2$ is known from external\ninformation, or\n\n(b) multiple measurements are available at each location, allowing the\ntwo sources of variation to be estimated separately.\n\nWe will explore the latter scenario in the next section.\n\nFor the Galicia data, we do not know the measurement device precision\nand we only have one observation per location. However, this does not\nprevent us from using the variogram based on the residuals from\n@eq-std-lm-galicia, while keeping in mind the limitations and\nuncertainty that are inherent to this exploratory tool as remarked at\nthe end of the last paragraph.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fitting of the linear model and extraction of the residuals\nlm_fit <- lm(log(lead) ~ 1, data = galicia)\n\n# Extract the raw residuals\ngalicia$residuals <- lm_fit$residuals\n\n# Compute the variogram, using the residuals from the linear model fit,\n# and the 95% confidence level envelope for spatial independence\ngalicia_variog <- variogram(\n  galicia,\n  variable = \"residuals\",\n  scale_to_km = TRUE,\n  breaks = seq(10, 140, length = 15),\n  n_permutations = 1000\n)\n\n# Plotting the results\nplot_variogram(galicia_variog, plot_envelope = TRUE)\n```\n\n::: {.cell-output-display}\n![Plot of the empirical variogram (solid line) computed using the estimated residuals from the model in @eq-std-lm-galicia. The blue shaded area is the 95% confidence level envelope generated using the permutation procedure described in @sec-expl-spatial.](03_model-fitting_files/figure-html/fig-galicia-variog-1.png){#fig-galicia-variog}\n:::\n:::\n\n\nIn the code above, we first fit the linear model in\n@eq-std-lm-galicia and then extract the residuals from this. Note that\nfor this simple model, the residuals of the model are obtained by simply\ncentering the log-transformed outcome to zero by subtracting its mean.\n@fig-galicia-variog shows the empirical variogram and the 95% envelope\nfor spatial independence. This clearly shows that the log-transformed\nlead concentrations are spatially correlated.\n\n##### More than one observation per location {#sec-explanal-lm}\n\nFor the case of more than one observation per location, we shall\nconsider the `italy_sim` dataset. This dataset contains 10 observations\nat each of 200 locations. The variable `ID_loc` is a numeric indicator\nthat can be used to identify the location each observation belongs to.\nFor this dataset, we use the population density, named `pop_dens`, as a\nlog-transformed covariate; we leave you as an exercise to assess whether\nit is a reasonable modelling choice.\n\nTo specify a non-spatial mixed model for the outcome, we then use two\nsubscripts: $i$ to identify a given location; $j$ to identify the $j$-th\nobservation for a given location $i$. We denote as $Z_i$ the\nlocation-specific random effect and as $U_{ij}$ the random variation due\nto the measurement error inherent to each observation. Hence, we write\n\n$$\nY_{ij} = \\beta_0 + \\beta_1 \\log\\{d(x_i)\\} + Z_i + U_{ij},\n$$ {#eq-italy-sim-lmm}\n\nwhere $d(x_i)$ is the population density at location $x_i$; as before,\nwe use $\\tau^2$ and $\\omega^2$ to denote the variances of $Z_i$ and\n$U_{ij}$, respectively. To fit this model to the data we use the `lmer()`\nfunction from the lme4 package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fitting a linear mixed model to the italy_sim dataset\n# See main text for model specification\nlmer_fit <- lmer(y ~ log(pop_dens) + (1 | ID_loc), data = italy_sim)\n```\n:::\n\n\n\n::: {#tbl-lmer-italy-sim .cell tbl-cap='Estimated parameters for the linear mixed model fitted to the Italy simulated data.'}\n::: {.cell-output-display}\n\n\n|Parameter  |Term                                  | Estimate| Std. error| t value|\n|:----------|:-------------------------------------|--------:|----------:|-------:|\n|$\\beta_0$  |Intercept                             |   -0.404|      0.576|  -0.702|\n|$\\beta_1$  |Log population density                |    1.338|      0.076|  17.506|\n|$\\tau^2$   |Location-level random-effect variance |    2.501|           |        |\n|$\\omega^2$ |Residual variance                     |    0.196|           |        |\n\n\n:::\n:::\n\n\nIn the model above, the introduction of the $Z_i$ random effect is\nspecified in the `lmer()` function through `(1 | ID_loc)` in the\nformula; recall that `ID_loc` is the numerical indicator that identifies\neach location. The estimates of the regression coefficients $\\beta_0$\nand $\\beta_1$, together with the variance components $\\tau^2$ and\n$\\omega^2$, are reported in @tbl-lmer-italy-sim. The location-level\nrandom-effect variance $\\tau^2$ is associated with `ID_loc`, while\n$\\omega^2$ is the residual variance.\n\nWe then extract the estimated location-specific random effects $Z_i$ and\nuse them to compute the empirical variogram. The code for carrying out\nthese steps is shown below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Incorporating the estimated random effects into the data\nitaly_sim$rand_eff <- ranef(lmer_fit)$ID_loc[italy_sim$ID_loc, 1]\n\n# Compute the variogram, using the random effects from the linear mixed model\n# fit, and the 95% confidence level envelope for spatial independence\nitaly_sim_variog <- variogram(italy_sim,\n  variable = \"rand_eff\",\n  scale_to_km = TRUE,\n  n_permutations = 1000\n)\n\n# Plot the variogram\nplot_variogram(italy_sim_variog, plot_envelope = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Plot of the empirical variogram (solid line) computed using the estimated random effects from the model in @eq-italy-sim-lmm. The blue shaded area is the 95% confidence level envelope generated using the permutation procedure described in @sec-expl-spatial.](03_model-fitting_files/figure-html/fig-italy-sim-variog-1.png){#fig-italy-sim-variog}\n:::\n:::\n\n\nThe application of the empirical variogram, whose results are shown in\n@fig-italy-sim-variog, indicates the presence of residual correlation.\nThis is because we observe that the solid line representing the\nempirical variogram falls outside of the 95% envelope for spatial\nindependence.\n\n## The linear geostatistical model {#sec-linear-model}\n\nIn this section, we focus on spatially referenced outcomes $Y_i$ that\nare continuous. We first consider the simpler case of a single\nmeasurement $Y_i$ per location $x_i$. Recalling the class of generalized\nlinear models introduced in @sec-geostat-models, the linear predictor\ntakes the form\n\n$$\n\\mu_{i} = d(x_i)^\\top \\beta + S(x_i).\n$$ {#eq-linear-geostat-model-lp}\n\nHence, in this case, we interpret\n$\\beta$ as the effect on $\\mu_i$ for a unit increase in $d(x_i)$. Let\n$U_i$ denote i.i.d. random variables representing the measurement error\nassociated with $Y_i$, each having mean zero and variance $\\omega^2$.\nThanks to the linear properties of Gaussian random variables, we can\nalso express the linear model in a compact expression, as\n\n$$\nY_i = \\mu_i + U_i = d(x_i)^\\top \\beta + S(x_i) + U_i.\n$$ {#eq-linear-geostat-model}\n\nTo fully specify a geostatistical model\nfor our dataset, we must address two critical aspects.\n\n1.  Defining the relationship between each covariate and the mean value\n    $\\mu_i$.\n\n2.  Selecting an appropriate correlation function for $S(x)$.\n\nAs illustrated in the previous sections, the initial step of exploratory\nanalysis allows us to handle the first aspect, where we determine the\nregression relationship between covariates and the mean value $\\mu_i$.\n\nHowever, based on existing methods of exploratory analysis, it is\ndifficult to understand what is a suitable correlation function at this\nstage. A commonly recommended starting point is the Matern correlation\nfunction (see @eq-matern), which offers considerable flexibility in\ncapturing a wide range of correlation structures, under the assumption\nof stationarity and isotropy. As we shall illustrate in the next\nexample, even estimating a Matern correlation function is a task that\nposes many inferential challenges, especially due to the poor\nidentifiability of its smoothness parameter $\\kappa$.\n\n### Evaluating the inclusion of the measurement error term $U_i$ and the specification of the smoothness parameter $\\kappa$ {#sec-glm-parest}\n\nIn this section we analyse the Galicia data using a linear\ngeostatistical model for the log-transformed lead concentration,\nrecalling that $Y_i = \\log(L_i)$. Since we do not use covariates, we\nthen write the model as\n\n$$\nY_i = \\mu + S(x_i) + U_i\n$$ {#eq-galicia-lgm}\n\nwhere were $S(x)$ is a Matern process with variance\n$\\sigma^2$, scale parameter $\\phi$ and and smoothness parameter\n$\\kappa$; the $U_i$ correspond to the measurement error term and denote\nwith $\\omega^2$ their variance.\n\nWe carry out the parameter estimation of the model using the `glgpm()`\nfunction from the RiskMap package. This function implements maximum\nlikelihood estimation for generalized linear mixed models using a Matern\ncorrelation function, while fixing the smoothness parameter $\\kappa$ at\na prespecified value. The object passed to the `data` argument must be\nan `sf` object with a coordinate reference system. The `galicia` dataset\nsupplied by RiskMap already satisfies these requirements.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Parameter estimation using the geometry and CRS stored in `galicia`\nfit_galicia <- glgpm(log(lead) ~ gp(kappa = 1.5),\n                     data = galicia, family = \"gaussian\",\n                     scale_to_km = TRUE, messages = FALSE)\n```\n:::\n\n\nThe Gaussian process $S(x)$ is specified through `gp()` in the formula.\nThe spatial coordinates and CRS are read directly from the `sf` geometry,\nwhile `kappa` fixes the smoothness parameter at 1.5. By default,\n`nugget = FALSE` and the nugget term (denoted in this book by $Z_i$) is\nexcluded. Set `nugget = TRUE` to estimate its variance, or pass a positive\nnumeric value to fix it. Estimating the nugget for a Gaussian model with\nonly one observation per location is not identifiable unless the\nmeasurement-error variance is fixed through `fix_var_me`; Exercise 7\nreturns to this point. The `scale_to_km` argument controls whether spatial\ndistances, and therefore the scale of $\\phi$, are expressed in kilometres\nor metres.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_galicia)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nglgpm(formula = log(lead) ~ gp(kappa = 1.5), data = galicia, \n    family = \"gaussian\", scale_to_km = TRUE, messages = FALSE)\n\nLinear geostatistical model\nLink: identity \nInverse link function = x \n\n'Lower limit' and 'Upper limit' refer to 95% confidence intervals\n\nRegression coefficients\n            Estimate Lower limit Upper limit   StdErr z.value\n(Intercept) 0.707418    0.552762    0.862075 0.078908  8.9651\n                          p.value    \n(Intercept) < 0.00000000000000022 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n                       Estimate Lower limit Upper limit\nMeasurement error var. 1.015584    0.012785      80.675\n\nSpatial Gaussian process\nMatern covariance parameters (kappa = 1.5)\n                     Estimate Lower limit Upper limit\nSpatial process var.  0.17127     0.10333      0.2839\nSpatial corr. scale   9.02085     5.38424     15.1137\nVariance of the nugget effect fixed at 0\n\nLog-likelihood: 69.03029\nAIC: -130.0606\n```\n\n\n:::\n:::\n\n\nWe can then inspect the point and interval estimates for the model\nthrough the `summary()` function of the model as shown in the code chunk\nabove. This output is presented in three sections: in the first section,\nwe have the results for the regression coefficients; in the second\nsection, we have the estimate for the variance of the measurement error\ncomponent, $\\omega^2$ whose point estimate is about 1.016; in the final\nsection, we have the estimates for the parameters of the spatial\ncovariance function, $\\sigma^2$ and $\\phi$ which are about 0.171 and\n9.021 (km), respectively. The message\n`Variance of the nugget effect fixed at 0` indicates that the nugget has\nnot been included in the mode.\n\nAt this point, you may be wondering, why we have used 1.5 for the value\nof $\\kappa$ and whether there is a statistical approach to find the most\nsuitable value for this. We show such an approach in the code below.\n\nHowever, before examining the code, we would like to point out an\nimportant aspect that relates to how the value of $\\kappa$ can affect\nthe estimate of the measurement error variance $\\omega^2$. As we have\nshown, in @sec-matern-correlation, values of $\\kappa$ that are closer to\nzero will give a rougher and less regular surface for $S(x)$. In the\ncase of a single observation, when $\\kappa$ is closer to zero, it will\nthus become increasingly difficult to estimate $\\omega^2$ since the\nlikelihood function may attribute most of the noisiness to $S(x)$ and\nrely less on $U_i$ to explain the unstructured random variation found in\nthe data. As a consequence of this, we can expect that for value of\n$\\kappa$ closer to zero, the estimates of $\\omega^2$ will also be\nsmaller and, on the contrary, when $\\kappa$ is larger, the estimates of\n$\\omega^2$ will also increase. The results generated in the code below\nclearly illustrate this point.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number of the values chosen for kappa\nn_kappa <- 10\n\n# Set of values for kappa\nkappa_values <- seq(0.5, 3.5, length = n_kappa)\n\n# Vector that will store the values of the likelihood function\n# evaluated at the maximum likelihood estimate\nllik_values <- rep(NA, length = n_kappa)\n\n# Vector that will store the maximum likelihood estimates\n# of the variance of the measurement error\nsigma2_me_hat <- rep(NA, length = n_kappa)\n\n# List that will contain all the geostatistical models fitted for\n# the different values of kappa specified in kappa_values\nfit_galicia_list <- list()\nfor (i in 1:n_kappa) {\n  formula_i <- as.formula(\n    sprintf(\"log(lead) ~ gp(kappa = %s)\", kappa_values[i])\n  )\n  fit_galicia_list[[i]] <- glgpm(formula_i,\n                                 data = galicia, family = \"gaussian\",\n                                 scale_to_km = TRUE, messages = FALSE)\n  llik_values[i] <- fit_galicia_list[[i]]$log.lik\n  sigma2_me_hat[i] <- coef(fit_galicia_list[[i]])[\"sigma2_me\"]\n}\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![(a) plot of the maximum likelihood estimate for the variance of the measurement error $U_i$, denoted in the text as $\\omega^2$, against the chosen fixed value for $\\kappa$; (b) profile likelihood for $\\kappa$ with the horizontal dashed line corresponding to the (approximate) threshold for constructing a 95% confidence interval based on a $\\chi^2$ with one degree of freedom. ](03_model-fitting_files/figure-html/fig-galicia-matern-1.png){#fig-galicia-matern fig-align='center' width=8.5in}\n:::\n:::\n\n\nBy examining the results shown in panel (a) of @fig-galicia-matern, we\nobserve that, as expected, smaller values for $\\kappa$ lead to smaller\npoint estimates for $\\omega^2$ and viceversa. This begs the question,\nwhat should be our chosen value for $\\kappa$?\n\nTo answer this question, a natural approach is to estimate the model for\ndifferent values of $\\kappa$ and see which one gives the best fit to the\ndata, according to the likelihood function. In panel (b) of\n@fig-galicia-matern, we show the results of this approach where we\nconsidered 10 values for $\\kappa$ within the range 0.5 to 3.5 (see code\nabove). In this plot, we have also added a horizontal line to help us to\napproximate a range of the most plausible value for $\\kappa$. More\nprecisely, the horizontal dashed line is computed by taking the maximum\nobserved values of the likelihoods computed for the different values of\n$\\kappa$, say $\\hat{M}$ and we subtract the quantile 0.95 of a $\\chi^2$\ndistribution with 1 degree of freedom. In R this horizontal line is\nobtained as\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmax(llik_values) - pchisq(0.95, df = 2) / 2\n```\n:::\n\n\nwhere `llik_values` is as defined in the previous chunk of code. Note\nthat this approach is essentially constructing the profile likelihood\nfor $\\kappa$ which one could use to derive a confidence interval for\n$\\kappa$ with a finer segmentation for `kappa_values`. However, our\ncurrent objective is not to derive the confidence interval for $\\kappa$,\nbut rather to gain a broad understanding of the $\\kappa$ values\nsupported by the dataset. The values of $\\kappa$ that correspond to\nlikelihood values above the horizontal line are approximately between\n0.75 and 2.75. Hence, selecting $\\kappa=1.5$ seems to be a reasonable\nchoice in this case. Now, you may be pondering: are there values other\nthan $\\kappa=1.5$ that could fit the data even better? Our answer is\nthat it is not worth the effort to try estimate $\\kappa$ more precisely\nbecause it is empirically very difficult and, under some scenarios, even\nimpossible. Estimating $\\kappa$ poses a well-documented challenge in\ngeostatistics (@zhang2004), which justifies our adoption of a pragmatic\napproach that sets it at a predefined value. This issue is also further\nexacerbated when analyzing count data, which tend to be less informative\nabout the correlation structure than continuously measured data.\n\n### Modelling hierarchical geostatistical data using the `re()` function {#sec-add-re-glgm}\n\nWe now consider the analysis of geostatistical data with a hierarchical\nstructure and show how to formulate and fit a geostatistical model that\naccounts for the effects of the different layers of the data. For this\npurpose, we use the `italy_sim` where each of the sampled locations can\nbe grouped according to two administrative subdivisions of Italy,\nregions (Admin level 2) and provinces (Admin level 3), as shown in\n@fig-italy-maps.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rgeoboundaries)\nlibrary(mapview)\nitaly_regions <- geoboundaries(country = \"italy\", adm_lvl = \"adm2\")\nitaly_provinces <- geoboundaries(country = \"italy\", adm_lvl = \"adm3\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\n\n# Map of the data with the region boundaries\nmap_regions <- ggplot() +\n  geom_sf(data = italy_sim, pch = 4, color = \"red\") +\n  geom_sf(data = italy_regions, fill = NA) +\n  theme_void() +\n  labs(title = \"Regions\") +\n  theme(plot.title = element_text(hjust = 1 / 2))\n\n# Map of the data with the province boundaries\nmap_provinces <- ggplot() +\n  geom_sf(data = italy_sim, pch = 4, color = \"red\") +\n  geom_sf(data = italy_provinces, fill = NA) +\n  theme_void() +\n  labs(title = \"Provinces\") +\n  theme(plot.title = element_text(hjust = 1 / 2))\n\nlibrary(gridExtra)\ngrid.arrange(map_regions, map_provinces, ncol = 2)\n```\n\n::: {.cell-output-display}\n![The plot shows the location of the dataset `italy_sim` (red crosses), with the boundaries of the regions (left) and provinces (right) of Italy.](03_model-fitting_files/figure-html/fig-italy-maps-1.png){#fig-italy-maps}\n:::\n:::\n\n\nLet $V_h$, for $h=1,\\ldots,n_V$ and $Z_k$, for $k=1,\\ldots,n_{Z}$, be a\nset of mutually independent Gaussian variables with zero means and\nvariances $\\sigma^2_{V}$ and $\\sigma^2_{Z}$, respectively. Finally let\n$\\mathcal{A}_h$, for $h=1,\\ldots,n_V$ and $\\mathcal{B}_k$, for\n$k=1,\\ldots,n_{Z}$, denote the areas encompassed by the boundaries of\nthe region and provinces, respectively. Since we have 10 repeated\nobservations at each locations, we shall use $Y_{ij}$ to denote the\n$j$-th outcome (found in the data under the column `y`) at the $i$-th\nlocation $x_i$. The model from which we generated data $y_{ij}$ is\n\n$$\n\\begin{aligned}\nY_{ij} = \\beta_0 &+ \\overbrace{\\beta_1 d(x_i) + S(x_i)}^\\text{Location-level effect} + \\underbrace{\\sum_{h=1}^{n_{V}} I(x_i \\in \\mathcal{A}_h) \\times V_h}_\\text{Region effect} \\\\\n&+ \\overbrace{\\sum_{k=1}^{n_{Z}} I(x_i \\in \\mathcal{B}_k) \\times Z_k}^\\text{Province effect} + \\underbrace{U_{ij}}_\\text{Measurement error}\n\\end{aligned}\n$$ {#eq-italy-sim-model}\n\nfor $j=1,\\ldots 10$ and $i=1,\\ldots,200$,\nwhere, $d(x_i)$ is the log-transformed population density,\n$I(x \\in \\mathcal{R})$ is an indicator function that takes value 1 if\nthe location $x$ falls within the boundaries of the area denoted by\n$\\mathcal{R}$ and 0 otherwise. The covariance function chosen in the\ngeneration of the data was an exponential correlation function hence\n${\\rm cov}\\{S(x), S(x') = \\sigma^2 \\exp\\{-||x-x'||/\\phi\\}$.\n\nThe inclusion of the random effects $V_h$, for the region, and $Z_k$,\nfor the province, can be included by using the `re()` function into the\n`formula` passed to `glgpm()` as shown below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Location-level, region, and province effects\nitaly_fit <- glgpm(y ~ log(pop_dens) + gp(kappa = 0.5, nugget = FALSE) +\n                     re(region, province),\n                   data = italy_sim, scale_to_km = TRUE,\n                   family = \"gaussian\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  0:     441.00731: -0.404481  1.33798  0.00000  4.62406  0.00000  0.00000  0.00000\n  1:    -130.05497: -0.408825  1.35003 -0.0387110  4.66059 -0.910409 -0.00265292 0.0107965\n  2:    -268.13436: -0.865126  1.39525 -0.0305269  5.92133 -1.96079 -0.666581 0.487537\n  3:    -329.24560: -1.44091  1.38139 -0.546306  4.98616 -1.67936 -1.15202 0.383821\n  4:    -331.20861: -1.38498  1.37256 0.165463  5.61366 -1.63033 -2.11435 0.371263\n  5:    -331.28418: -0.874796  1.37322 -0.271990  5.18071 -1.62887 -0.970704 0.371407\n  6:    -331.42968: -1.04087  1.37294 -0.119652  5.33634 -1.62883 -1.33321 0.375031\n  7:    -331.43375: -1.07312  1.37288 -0.0878211  5.36725 -1.62883 -1.42011 0.376251\n  8:    -331.43375: -1.07445  1.37288 -0.0866254  5.36840 -1.62883 -1.42489 0.376323\n  9:    -331.43375: -1.07445  1.37288 -0.0866227  5.36840 -1.62883 -1.42491 0.376323\n 10:    -331.43375: -1.07445  1.37288 -0.0866227  5.36840 -1.62883 -1.42491 0.376323\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(italy_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nglgpm(formula = y ~ log(pop_dens) + gp(kappa = 0.5, nugget = FALSE) + \n    re(region, province), data = italy_sim, family = \"gaussian\", \n    scale_to_km = TRUE)\n\nLinear geostatistical model\nLink: identity \nInverse link function = x \n\n'Lower limit' and 'Upper limit' refer to 95% confidence intervals\n\nRegression coefficients\n               Estimate Lower limit Upper limit    StdErr z.value\n(Intercept)   -1.074454   -2.031694   -0.117213  0.488397  -2.200\nlog(pop_dens)  1.372877    1.331160    1.414593  0.021284  64.501\n                           p.value    \n(Intercept)                0.02781 *  \nlog(pop_dens) < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n                       Estimate Lower limit Upper limit\nMeasurement error var.   1.2167      1.1398      1.2988\n\nSpatial Gaussian process\nMatern covariance parameters (kappa = 0.5)\n                      Estimate Lower limit Upper limit\nSpatial process var.   0.91702     0.25011      3.3622\nSpatial corr. scale  214.52032    56.39618    815.9944\nVariance of the nugget effect fixed at 0\n\nUnstructured random effects\n                            Estimate Lower limit Upper limit\nregion (random eff. var.)   0.240530    0.011797      4.9041\nprovince (random eff. var.) 1.456918    0.989156      2.1459\n\nLog-likelihood: 331.4338\nAIC: -648.8675\n```\n\n\n:::\n:::\n\n\nIn the code above, the `factor` variables `region` and `province` found\nin `italy_sim` are passed to `re()` and these are estimated as\nunstructured random effects as defined by @eq-italy-sim-model. From the\nsummary of the model, we then obtain the parameter and interval\nestimates as reported in @tbl-italy-sim-mle.\n\n| Parameter      | Point estimate | Lower limit | Upper limit |\n|----------------|----------------|-------------|-------------|\n| $\\beta_0$      | -1.074         | -2.032      | -0.117      |\n| $\\beta_1$      | 1.373          | 1.331       | 1.415       |\n| $\\sigma^2$     | 0.917          | 0.250       | 3.362       |\n| $\\phi$         | 214.520        | 56.396      | 815.994     |\n| $\\sigma^2_{V}$ | 0.241          | 0.012       | 4.904       |\n| $\\sigma^2_{Z}$ | 1.457          | 0.989       | 2.146       |\n| $\\omega^2$     | 1.217          | 1.140       | 1.299       |\n: Maximum likelihood estimates and, lower and upper limits of the 95%\nconfidence interval for the parameters of the model in\n@eq-italy-sim-lmm. {#tbl-italy-sim-mle}\n\nThe function `to_table()` from the RiskMap package can be used to obtain\nthe Latex or HTML code directly from a fit of the model. Here is an\nexample.\n\n\n::: {#tbl-italy-spatial-mixed-model .cell}\n\n```{.r .cell-code}\nto_table(italy_fit, digits = 3)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Estimate\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Lower limit\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Upper limit\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"-1.0744535\",\"2\":\"-2.03169414\",\"3\":\"-0.1172129\",\"_rn_\":\"(Intercept)\"},{\"1\":\"1.3728765\",\"2\":\"1.33115983\",\"3\":\"1.4145932\",\"_rn_\":\"log(pop_dens)\"},{\"1\":\"0.9170230\",\"2\":\"0.25011048\",\"3\":\"3.3622388\",\"_rn_\":\"Spatial process var.\"},{\"1\":\"214.5203218\",\"2\":\"56.39617967\",\"3\":\"815.9944299\",\"_rn_\":\"Spatial corr. scale\"},{\"1\":\"0.2405302\",\"2\":\"0.01179727\",\"3\":\"4.9040829\",\"_rn_\":\"region (random eff. var.)\"},{\"1\":\"1.4569178\",\"2\":\"0.98915642\",\"3\":\"2.1458785\",\"_rn_\":\"province (random eff. var.)\"},{\"1\":\"1.2167193\",\"2\":\"1.13980889\",\"3\":\"1.2988195\",\"_rn_\":\"Measurement error var.\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## Generalized linear geostatistical models\n\nWe now consider the modelling of count outcomes, focusing our attention\nto the Binomial and Poisson geostatistical models.\n\nThe use of Binomial geostatistical model is appropriate whenever the\nreported counts have a known upper bound. For example, when analyzing\naggregated disease counts from cross-sectional survey data, the total\nnumber of people sampled at a location defines the largest number of\npossible reported disease cases. Recalling the model specification of\n@tbl-glm, we specify the Binomial geostatistical model by stating that\nthe reported disease counts $Y_i$ out of $n_i$ (the maximum value that\n$Y_i$ can take) at location $x_i$, conditionally on the spatial random\neffects $S(x_i)$, follow a Binomial distribution with probability\n$p(x_i)$ and logit-linear predictor\n\n$$\n\\log\\left\\{\\frac{p(x_i)}{1-p(x_i)}\\right\\} = d(x_i)^\\top \\beta + S(x_i).\n$$ {#eq-lp-bin}\n\nIn this model, $p(x_i)$ is commonly understood as\nrepresenting the prevalence of the disease under consideration, defined\nas the proportion of individuals with the disease at a specific moment.\nWhile $p(x_i)$ is not strictly a proportion, its interpretation as\ndisease prevalence is justified by the fact that if we were to sample a\nsufficiently large population at location $x_i$, the proportion of\nindividuals with the disease would converge closely to the value of\n$p(x_i)$.\n\nA Binomial geostatistical model is also used when analyzing data at\nindividual level where the outcome is binary and usually indicates the\npositive or negative result of a test for a disease under investigation.\nIn this analysis, a mix of individual-level variables and location-level\nvariables could be introduced to model the probability of a positive\ntest. To formally write the model, we now use $Y_{ij}$ to indicate the\nbinary outcome taking value 1, if the test was positive, and 0, if\nnegative, for the $j$-th individual sampled at location $x_i$. The\nlinear predictor now takes the form\n\n$$\n\\log\\left\\{\\frac{p_{ij}}{1-p_{ij}}\\right\\} = e_{ij}^\\top \\gamma + d(x_{i})^\\top \\beta + S(x_i).\n$$ {#eq-lp-bin-ind}\n\nIn the model above we have distinguished between\ncovariates $e_{ij}$, that express the effect on $p_{ij}$ due to\nindividual traits (such as age and gender), and covariates $d(x_i)$,\nthat instead quantify the effect on $p_{ij}$ resulting from the\nenvironmental attributes of location $x_i$ (such as elevation,\ntemperature, and precipitation). In this model $p_{ij}$ -- the\nprobability of a positive test -- once again can be interpreted as the\ndisease prevalence for a population characterized by the individual\ntraits $e_{ij}$ and residing at location $x_i$.\n\nFinally, when the counts arise from a population whose size is unknown\nor when the occurrence of a disease is very small relative to the size\nof the target population, one should consider the use of a Poisson\ngeostatistical model. We then use $Y_i$ to denote the reported counts at\nlocation $x_i$ and assume that this, conditionally on a Gaussian process\n$S(x_i)$, follows a Poisson distribution with mean $\\lambda(x_i)$ and\nlog-linear predictor\n\n$$\n\\log\\left\\{\\lambda(x_i)\\right\\} = d(x_i)^\\top \\beta + S(x_i).\n$$ {#eq-poisson-lp}\n\nIf for example, $Y_i$ corresponds to the number of\nnew cases reported at a health facility at location $x_i$ over a\ncertain, the $\\lambda(x_i)$ is interpreted as the average number of new\ncases reported over that period. If the information on the size of the\npopulation at risk for the diseases were available, this can be\nincorporated into the model so as to enable the interpretation of\n$\\lambda(x_i)$ as the disease incidence, defined as the total number of\nnew cases reported over a given period of time divided by the population\nat risk. If we denote the latter as $m_i$, then we would specify the\nmean of $Y_i$ as $m_i\\lambda(x_i)$ an model $\\lambda(x_i)$ as already\nspecified in @eq-poisson-lp. Another prevalent application of the\nPoisson geostatistical model in epidemiology involves mapping the\nabundance of disease vectors. Here, $\\lambda(x_i)$ corresponds to the\nmean number of vectors per unit area. Also, note that in this last\nscenario $m_i$ cannot be defined as it is the goal of the analysis to\ninfer the vector population size at location $x_i$.\n\nIn all the three models, namely @eq-lp-bin, @eq-lp-bin-ind and\n@eq-poisson-lp, one might consider the inclusion of an additional random\neffect $Z_i$, previously used for the linear geostatistical model, to\naccount for small spatial variation or overdispersion that stems from\nthe omission of covariates that may not necessarily exhibit spatial\nstructure, such as behavioral or genetic traits. We shall further\nelaborate and provide guidance on this point in the following examples\nof this section.\n\n### Example: river-blindness in Liberia {#sec-liberia-estim1}\n\nIn section @sec-agg-count-exp, we carried out the exploratory analysis\nof the river-blindness prevalence data to assess how elevation could be\nintroduced into the model. In @sec-empirical-variog-bin, we then tested\nfor residual spatial correlation using the empirical variogram and\nlog-transformed elevation as a covariate. Based on these results, we can\nnow formulate a Binomial geostatistical model which we then fit to the\ndata. Hence, we extend the model presented in @eq-liberia-bin-mixed-elev\nthrough the inclusion of a spatial Gaussian process, $S(x)$, and write\n$$\n\\log\\left\\{\\frac{p(x_i)}{1-p(x_i)}\\right\\} = \\beta_{0} + \\beta_{1}\\log\\{e(x_i)\\} + S(x_i) + Z_i.\n$$ {#eq-liberia-geostat-bin-elev}\n\nWe shall assume that $S(x_i)$ is a\nstationary isotropic Gaussian process with an exponential correlation\nfunction function $\\rho(u) = \\exp\\{-u/\\phi\\}$, with scale parameter\n$\\phi$.\n\nWe apply the Monte Carlo Maximum Likelihood (MCML) method for parameter\nestimation, which is implemented via the `glgpm()` function. In this\nsection, we set aside the technical details of the estimation process to\nfocus exclusively on interpreting the results. A more detailed\nexplanation of the MCML theory can be found in @sec-glgm-lik, with a\nconcise summary of the practical aspects provided in @sec-summary.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_liberia <- glgpm(npos ~ log(elevation) + gp(),\n                     den = ntest, data = liberia,\n                     convert_to_crs = 32629,\n                     family = \"binomial\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  0:    -0.0000000: -2.99847 0.313076  0.00000  4.18370\n  1:    -7.3358316: -2.89179 0.279759 -0.674057  4.78794\n  2:    -12.195563: -2.99160 0.312424 -1.19363  4.02702\n  3:    -12.972832: -3.03446 0.319790 -1.73015  3.26903\n  4:    -13.535188: -3.02529 0.318080 -1.56352  3.39231\n  5:    -13.559246: -3.02898 0.318738 -1.52363  3.44477\n  6:    -13.559376: -3.02920 0.318775 -1.52036  3.44890\n  7:    -13.559376: -3.02920 0.318775 -1.52034  3.44893\n  8:    -13.559376: -3.02920 0.318775 -1.52034  3.44893\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit_liberia)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nglgpm(formula = npos ~ log(elevation) + gp(), data = liberia, \n    family = \"binomial\", den = ntest, convert_to_crs = 32629)\n\nBinomial geostatistical model\nLink: canonical \nInverse link function = plogis(x) \n\n'Lower limit' and 'Upper limit' refer to 95% confidence intervals\n\nRegression coefficients\n                Estimate Lower limit Upper limit    StdErr  z.value\n(Intercept)    -3.029198   -3.560179   -2.498216  0.270914 -11.1814\nlog(elevation)  0.318775    0.216296    0.421254  0.052286   6.0967\n                             p.value    \n(Intercept)    < 0.00000000000000022 ***\nlog(elevation)        0.000000001083 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSpatial Gaussian process\nMatern covariance parameters (kappa = 0.5)\n                     Estimate Lower limit Upper limit\nSpatial process var.  0.21864     0.14329      0.3336\nSpatial corr. scale  31.46671    17.41642     56.8518\nVariance of the nugget effect fixed at 0\n\nLog-likelihood: 13.55938\n```\n\n\n:::\n:::\n\n\nWhen using the `glgpm()` function to fit a Binomial model, we need to\nspecify the Binomial denominators, i.e. the number of people tested at a\nlocation in this case, through the argument `den`. Other arguments of\n`glgpm()` that are used for carrying out MCML are `control_mcmc()`, that\ndefines the setting parameters of the Monte Carlo Markov Chain\nalgorithm, and `par0`, which represents our best guess for the unknown\nparameters of the Binomial geostatistical model. For more information on\nthe default values of these two arguments, we refer you to the help page\nof the `glgpm()` function. To understand how to change the default\nparameters in order to improve the MCML estimation, we advise you to\nread @sec-mcml. Also, remember that to enable the estimation of the\nnugget effect, $Z_i$, you should set `nugget=TRUE` in the `gp()` function,\nsince by default the `glgpm()` function excludes $Z_i$.\n\nIn the above summary of the model, the interpretation of the regression\ncoefficients is the same as in a standard logistic regression model.\nHence, by taking the exponential of the estimate for the regression\ncoefficient $\\beta_1$, we can express the effect for a unit increase in\nthe covariate -- in this case the log-transformed elevation -- on the\nodds of disease prevalence. Finally, the interpretation of estimates of\nthe covariance parameters is not affected by the type of distribution\nused to model the main outcome. From the above summary, we note the\nlarger estimates of $\\sigma^2$ than $\\tau^2$ which suggest the dominance\nof spatial variation over the unstructured variation in the unexplained\nvariation of disease prevalence. Finally, the estimate of $\\phi$\nindicates a relatively large spatial correlation with a *practical\nrange* close to ($58.67 \\times 3 \\approx$)180km.\n\n### Example: *Anopheles Gambiae* mosquitoes in Cameroon {#sec-anopheles-fit}\n\nIn @sec-agg-count-exp, we explored the association between elevation and\nthe number of mosquitoes and found that the data showed that on average,\nthe number of *Anopheles Gambiae* (A. Gambiae) decreases for increasing\nelevation. We now fit a log-linear Poisson geostatistical model, with\nlinear predictor\n\n$$\n\\lambda(x_i) = \\beta_0 + \\beta_1 d(x_i) + S(x_i)\n$$ {#eq-anopheles}\n\nwhere $d(x_i)$ corresponds to the elevation in meters\nat location $x_i$. The `anopheles` dataset is provided as an `sf` object.\nWe can then use the following script to fit the model in RiskMap.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nan_fit <- glgpm(An.gambiae ~ elevation + gp(),\n                data = anopheles,\n                family = \"poisson\", messages = FALSE)\nsummary(an_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nglgpm(formula = An.gambiae ~ elevation + gp(), data = anopheles, \n    family = \"poisson\", messages = FALSE)\n\nPoisson geostatistical model\nLink: canonical \nInverse link function = exp(x) \n\n'Lower limit' and 'Upper limit' refer to 95% confidence intervals\n\nRegression coefficients\n               Estimate Lower limit Upper limit      StdErr z.value\n(Intercept)  3.69384399  3.00784989  4.37983809  0.35000342 10.5537\nelevation   -0.00283997 -0.00388148 -0.00179847  0.00053139 -5.3444\n                          p.value    \n(Intercept) < 0.00000000000000022 ***\nelevation            0.0000000907 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSpatial Gaussian process\nMatern covariance parameters (kappa = 0.5)\n                     Estimate Lower limit Upper limit\nSpatial process var.  0.67165     0.47849      0.9428\nSpatial corr. scale   4.38649     2.59650      7.4105\nVariance of the nugget effect fixed at 0\n\nLog-likelihood: 9.453628\n```\n\n\n:::\n:::\n\n\nThe estimate, $\\hat{\\beta}_1$, for the regression coefficient $\\beta_1$\nsuggests that for a 100 meters drop in elevation, the average number of\nmosquitoes decreases by about\n$(100\\times\\exp\\{100\\times -0.018\\}\\approx)17\\%$. The order of magnitude\nof the estimates suggest the presence of residual spatial correlation,\nalbeit on a rather small scale.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndist_summaries(anopheles, scale_to_km = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$min\n[1] 0.3828559\n\n$max\n[1] 160.388\n\n$mean\n[1] 54.58734\n\n$median\n[1] 43.70518\n```\n\n\n:::\n:::\n\n\nUsing the `dist_summaries()` function, we can see that, among the\nlocations of the dataset, the average distance is about 55km and the\nminimum is about 387 meters. The estimate of phi of 4km is thus\nrelatively small compared to the distances between locations in the\ndata. In @sec-geo-prediction, we will further investigate to what extent\nthis small-scale spatial correlation can affect the predictions of the\nAn. Gambiae counts.\n\n### Using parametric bootstrap for computing confidence intervals {#sec-bootstrap}\n\n\n::: {.cell}\n\n:::\n\n\nThe bootstrap is a widely used resampling technique introduced by\n@efron1979 as a general approach to estimating the variability of\nstatistical estimates without relying on strong parametric assumptions.\n\nWhile the classical non-parametric bootstrap resamples directly from the\nobserved data, parametric bootstrap instead relies on simulating new\ndatasets from an assumed parametric model, using plug-in estimates\nobtained from the original fit of the model to the data. This\nsimulation-based method is particularly useful for complex models, such\nas those considered in this book, that yield an intractable likelihood\nfunction.\n\nWe now describe how to carry out parametric bootstrap for geostatistical\nmodels in RiskMap. The use of simulation-based approaches will be more\nextensively covered in @sec-geo-prediction, but, for the purpose of this\nsection, it is first important to understand how data can be simulated\nfrom a geostatistical model.\n\nThe way we have formulated geostatistical models in @sec-geostat-models\nprovides a hint as to what step should be followed when simulating from\na geostatistical model. Using the same notation of @sec-geostat-models,\nthese are the steps.\n1.  For a given set of predefined locations $X$ compute the covariance\n    matrix $\\Sigma$ with $(i,j)$-th entry $\\sigma^2 \\rho(u_{ij})$.\n2.  Compute the covariate effects $d(x)^\\top \\beta$ for all the\n    locations in $X$.\n3.  Simulate $B$ times from a multivariate Gaussian distribution with\n    mean vector 0 and covariance $\\Sigma$ as previously defined. We\n    denote the output from this step as $S_{(j)}(x)$, for\n    $j = 1, \\ldots, B$.\n4.  Compute the linear predictor at each location of $X$, by adding the\n    covariate effects from step 2 to the simulated random effects from\n    step 3, hence $g\\{\\mu_{(j)}(x)\\} = d(x)^\\top \\beta + S_{(j)}(x)$.\n\nNote that before performing the steps above, the values of the model\nparameters must be fixed. For example, if simulating from a model fitted\nto the data, the values of the model parameters should be the maximum\nlikelihood estimates. If the goal is to simulate actual observations for\nthe outcome $Y$ at the locations $X$, then we need to add the following\nsteps.\n5A. If the nugget term is included in the model, draw samples $Z_{(j)}$\nfor each location in $X$ from a Gaussian distribution with mean 0 and\nvariance $\\tau^2$. Add the simulated values $Z_{(j)}$ to\n$g\\{\\mu_{(j)}(x)\\}$.\n6A. Compute $\\mu_{(j)}(x)$ by applying the inverse link function\n$g^{-1}(\\cdot)$ to the samples of the linear predictor previously\ncomputed.\n7A. Simulate from the distribution of $Y$ given $\\mu_{(j)}(x)$,\naccording to the chosen model, for $j = 1, \\ldots, B$.\n\nThese steps, from 1 to 7A, have been implemented in the `glgpm_sim()`\nfunction. To show how to perform parametric bootstrap in RiskMap, let\nus consider the Liberia data on riverblindness and fit the following\ngeostatistical model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_liberia_no_nugget <- glgpm(npos ~ log(elevation) + gp(),\n                               den = ntest, data = liberia,\n                               convert_to_crs = 32629,\n                               family = \"binomial\")\n```\n:::\n\n\nUsing the fitted Binomial geostatistical above, we can simulate a single\ndataset as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nliberia_sim <- glgpm_sim(n_sim = 1, model_fit = fit_liberia_no_nugget)\n```\n:::\n\n\nThe output `liberia_sim` is a list with as many components as indicated\nby `n_sim`. In this case, we can access the simulated dataset as\n`liberia_sim[[1]]`. For example, we could refit the same model to the\nsimulated data as\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_liberia_no_nugget_sim <- glgpm(formula = npos ~ log(elevation) + gp(),\n                                   data = liberia_sim[[1]],\n                                   family = \"binomial\", den = ntest)\n```\n:::\n\n\nNote that if the data's CRS has been converted, the simulated dataset\nwill inherit the new CRS rather than the original. This means that any\ntransformation applied to the CRS before simulation (e.g., from\ngeographic to projected coordinates) will affect the spatial scale and\ninterpretation of the simulated data.\n\nThis idea can be extended naturally to perform parametric bootstrap. The\nprocedure involves simulating multiple datasets from the fitted model,\nrefitting the model to each of them, and extracting the estimates of\ninterest. For instance, the following code simulates 100 datasets and\nfits the same model to each, storing the estimated regression\ncoefficients:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulate 100 datasets\nn_sim <- 100\nliberia_boot <- glgpm_sim(n_sim = n_sim, model_fit = fit_liberia_no_nugget)\n\n# List where we will store the estimates from each of the simulated datasets\npar_hat <- list()\nfor (i in 1:n_sim) {\n\n  # Extracting the simulated Binomial data into \"npos_sim\"\n  liberia_boot$data_sim$npos_sim <- liberia_boot$data_sim[[paste(\"npos_sim\", i, sep = \"\")]]\n\n  # Fitting the geostatistical model\n  fit_sim <- glgpm(formula = npos_sim ~ log(elevation) + gp(),\n                   data = liberia_boot$data_sim,\n                   family = \"binomial\",\n                   par0 = coef(fit_liberia_no_nugget),\n                   den = ntest)\n\n  # Extracting the parameter estimates\n  par_hat[[i]] <- coef(fit_sim)\n}\n```\n:::\n\n\nAfter obtaining the parameter estimates, we extract them and rearrange\nthem in a matrix format to facilitate the computation of any summary,\nincluding the confidence intervals as shown in the code below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract all parameters maintaining beta as a vector\nall_params <- sapply(1:n_sim, function(i) {\n  c(\n    par_hat[[i]]$beta,\n    par_hat[[i]]$sigma2,\n    par_hat[[i]]$phi\n  )\n})\nCI <- t(apply(all_params, 1, function(x) quantile(x, c(0.025, 0.975))))\np <- 2\nrownames(CI)[(p + 1):(p + 2)] <- c(\"sigma^2\", \"phi\")\nsummary(fit_liberia_no_nugget)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nglgpm(formula = npos ~ log(elevation) + gp(), data = liberia, \n    family = \"binomial\", den = ntest, convert_to_crs = 32629)\n\nBinomial geostatistical model\nLink: canonical \nInverse link function = plogis(x) \n\n'Lower limit' and 'Upper limit' refer to 95% confidence intervals\n\nRegression coefficients\n               Estimate Lower limit Upper limit   StdErr  z.value\n(Intercept)    -3.22873    -3.67545    -2.78201  0.22792 -14.1658\nlog(elevation)  0.35031     0.26327     0.43735  0.04441   7.8881\n                             p.value    \n(Intercept)    < 0.00000000000000022 ***\nlog(elevation)  0.000000000000003069 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSpatial Gaussian process\nMatern covariance parameters (kappa = 0.5)\n                     Estimate Lower limit Upper limit\nSpatial process var.  0.23985     0.15154      0.3796\nSpatial corr. scale  37.32475    18.44717     75.5204\nVariance of the nugget effect fixed at 0\n\nLog-likelihood: 13.7532\n```\n\n\n:::\n\n```{.r .cell-code}\nCI\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     2.5%      97.5%\n(Intercept)    -3.9992335 -2.5240527\nlog(elevation)  0.2135445  0.5091142\nsigma^2         0.1114562  0.3610035\nphi            11.7567799 71.5459459\n```\n\n\n:::\n:::\n\n\nBy comparing the 95$\\%$ confidence intervals obtained from the `summary()`\nof the fitted model with those derived from the bootstrap approach, we\nobserve that the former are considerably narrower for the covariance\nparameters, while the intervals are fairly similar for the regression\ncoefficients.\n\nThis discrepancy arises because the Wald-type confidence intervals from\n`summary()` rely on a Gaussian approximation of the maximum likelihood\nestimator for the covariance parameters, which may not be entirely\nreliable. (To improve the accuracy of this approximation, RiskMap\napplies it to the log-transformed parameters and then transforms the\nconfidence intervals back to the original scale.) On the other hand,\nbootstrap-based confidence intervals tend to be more reliable, as they\nare not dependent on the Gaussian assumption. However, they are also\nmore computationally demanding. The use of only 100 bootstrap samples,\nas shown above, may indeed be insufficient. It is generally recommended\nto use at least 1000 iterations, if computationally feasible, to\nminimize the Monte Carlo error arising from the bootstrap simulations.\n\n## The residuals of a geostatistical model: issues to consider\n\nIn geostatistical models, the concept of residuals, which are widely\nused in regression modelling to carry out model diagnostics, becomes\nmore nuanced than in standard regression models (i.e., models that do\nnot include random effects) . Generally, residuals aim to quantify the\ndiscrepancy between observed outcomes and what the model predicts.\n\nHowever, in GLGMs, there are multiple valid definitions of residuals.\nIf we define the residuals as the component of the model that expresses\nthe variation in the outcome not explained by the covariates, then we\nare effectively referring to the random effects component of the linear\npredictor—i.e. $S(x_i)$, or $S(x_i) + Z_i$ if a nugget effect $Z_i$ is\nincluded. We refer to these as *random effects residuals*.\n\nLet $W_i$ denote the sum of all the random effects in the model, whether\n$W_i = S(x_i)$, $W_i = S(x_i) + Z_i$, or any other random effects\nstructure. In addition to RERs, other types of residuals more common in\nstandard regression modeling can also be used, however, because of the\npresence of random effects $W_i$, their definition becomes more\nconvoluted.\n\nLet us consider the *Pearson residuals*. Conditionally on $W_i$ we can\ndefine these as:\n\n$$\n\\operatorname{PR}_i(W_i) =\n\\frac{y_i - \\widehat{\\operatorname{E}}[Y_i]}\n{\\sqrt{\\widehat{\\operatorname{Var}}[Y_i]}}\n$$\n\nwhere $\\widehat{\\operatorname{E}}[Y_i]$ and\n$\\widehat{\\operatorname{Var}}[Y_i]$ are estimates of the predictive\nexpectation and variance of $Y_i$. Using Monte Carlo samples, say\n$W_{i,(j)}$ for $j = 1, \\ldots, B$, from the distribution of $W_i$ given\nthe data (see @sec-mcmc-mala for how these samples are generated in\nRiskMap), the expectations can be estimated as:\n\n$$\n\\widehat{\\operatorname{E}}[Y_i]\n= \\frac{1}{B} \\sum_{j=1}^B\n\\widehat{\\operatorname{E}}[Y_i \\mid W_{i,(j)}], \\quad\n\\widehat{\\operatorname{Var}}[Y_i]\n= \\frac{1}{B} \\sum_{j=1}^B\n\\widehat{\\operatorname{Var}}[Y_i \\mid W_{i,(j)}]\n$$\n\nAn alternative, especially useful when $Y_i$ is binary, is the *deviance\nresidual*:\n$$\n{\\rm DR}_i = \\text{sign}(y_i - \\hat{y}_i) \\sqrt{2 \\left( \\ell_i^{S} - \\ell_i^{F} \\right)}\n$$\nwhere $\\ell_i^{S}$ is the log-likelihood of the so-called *saturated\nmodel*, and $\\ell_i^{F}$ is the log-likelihood of the fitted model, both\nconditional on $W_i$. The saturated model is a hypothetical model that\nfits the data **perfectly**, meaning it has as many parameters as data\npoints. In such a model, the predicted values are exactly equal to the\nobserved values, and therefore the log-likelihood reaches its maximum\npossible value. This model serves as a benchmark or upper bound against\nwhich the fit of any other model, including our fitted model, is\ncompared. Hence, the difference $\\ell_i^{S} - \\ell_i^{F}$ reflects how\nmuch worse our model fits the data compared to this idealized scenario.\n\nWhile the residuals discussed above can provide useful insights into\nmodel fit, they are often less informative in the context of count data,\nespecially for binary data and low counts. Moreover, even in the simpler\ncase of linear geostatistical models where all three types of residuals\nintroduced earlier (random effects residuals, Pearson residuals, and\ndeviance residuals) are mathematically equivalent, it is easy to show\nthat the correlation structure of the estimated residuals is related to\nthe spatial correlation matrix of the fitted geostatistical model (see\n@sec-h-matrix). Whether this correlation in the estimated residuals is\nunimportant or poses a problem, particularly when using residuals to\nassess whether spatial dependence has been fully accounted for by the\nmodel, is still an open question and requires further investigation.\n\nGiven these complexities, especially in the context of count data, we\nhave chosen not to delve deeper into residual diagnostics in this\nedition of the book. Instead, model validation will be addressed more\ncomprehensively in the context of geostatistical prediction in\n@sec-geo-prediction.\n\nNevertheless, we note that some standard diagnostic tools from\nregression analysis (such as scatter plots of fitted values versus\nresiduals) can still be informative and are worth exploring as part of\nroutine model assessment [Chapter 9, @weisberg2014].\n\n## Theory\n\n### Maximum likelihood estimation for non-Gaussian mixed models with independent random effects\n\nIn this section, we provide more technical details on the derivation of\nthe likelihood function for the mixed model specified in\n@eq-linear-predictor-glmms-ch2. While not essential for understanding\nthe application and interpretation of geostatistical models, this\nsection provides useful insights into computational challenges inherent\nto the models presented in this book. In this section, we restrict our\nattention to the case when the outcome $Y_i$ is a count.\n\nLet $\\theta = (\\beta, \\tau^2)$ denote the vector of unknown parameters,\nwhere $\\beta$ is the vector of regression coefficients and $\\tau^2$ is\nthe variance of the random effects $Z = (Z_1, \\ldots, Z_n)$. The\nlikelihood function for a set of observations $Y = (Y_1, \\ldots, Y_n)$,\nfor $i=1,\\ldots,n$, under the model in @eq-linear-predictor-glmms-ch2,\nis obtained by deriving the marginal distribution of $Y_i$, hence\n\n$$\nL(\\theta) = [Y] = \\int_{R^n} \\: [Z] [Y \\:|\\: Z] \\: d Z\n$$\n\nSince the elements $Z_i$ in $Z$ are mutually independent, we can\nwrite\n\n$$\n[Z] = \\prod_{i=1}^n [Z_i]\n$$\n\nand, using the conditional independence among the $Y$ given $Z$, we\nobtain\n\n$$\n[Y \\:|\\: Z] = \\prod_{i=1}^n [Y_i | Z_i].\n$$\n\nFrom these, it then follows that\n\n$$\nL(\\theta) = \\int_{R^n} \\: \\prod_{i=1}^n [Z_i] \\prod_{i=1}^n [Y_i | Z_i] \\: d Z = \\prod_{i=1}^n \\int_{R} \\: [Z_i] [Y_i \\:|\\: Z_i] \\: d Z_i.\n$$ {#eq-glmm-final}\n\nThis shows that under the model in\n@eq-linear-predictor-glmms-ch2, whilst accounting for overdispersion,\nthis model does not account for any source of correlation between the\nobservations. This is because the likelihood function can be expressed,\nas shown in the equation above, as the product of $n$ likelihoods\nassociated with each of the observations.\n\nAnother important observation is that the integrals that express the\nlikelihood in @eq-glmm-final, cannot be solved analytically and need to\nbe approximated. Several solutions are available that are either based\non maximum likelihood estimation or Bayesian methods of inference. The\nfunction `glmer()` used in @sec-empirical-variog-lm provides both the\nLaplace and Gaussian quadrature approximations options. The former\nconsists of finding the *peak* of the integrand - i.e. the function that\nis being integrated - and approximating that with a Gaussian\ndistribution centered at that *peak*, using the curvature of the\noriginal distribution to determine the width of the Gaussian\ndistribution. The Gaussian quadrature is another numerical integration\ntechnique used to approximate the integral of a function. It involves\nchoosing specific points (nodes) and weights within the integration\ninterval to approximate the integral. By strategically selecting these\npoints and weights based on a Gaussian distribution, Gaussian quadrature\ncan provide highly accurate results compared to other numerical\nintegration methods, such as the Laplace approximation. For a\ncomprehensive overview of these and other methods of approximations of\nintractable integrals, we consider @bishop2006 to be an accessible\ntextbook on this topic.\n\n### Maximum likelihood estimation for non-Gaussian generalized linear geostatistical models {#sec-glgm-lik}\n\nTo derive the likelihood function of a generalized linear geostatistical\nmodel (GLGM), we consider the special case of a single observation per\nlocation without loss of generality. Let $Y$ and $Z$ denote the same\nvectors of random variables introduced in the previous section, with\ncomponents $Y_i$ and $Z_i$ corresponding to the set of locations\n$X = (x_1, \\ldots, x_n)$. Additionally, we define\n$S(X) = (S(x_1), \\ldots, S(x_n))$ to represent the spatial Gaussian\nprocess at the sampled locations $X$. In this case the vector of unknown\nparameters is $\\theta = (\\beta, \\sigma^2, \\phi, \\tau^2)$ and, as done in\nthe previous section, we can obtain the likelihood function though the\nmarginal distribution of the data, hence we write\n\n$$\nL(\\theta) = [Y] = \\int_{R^n} \\int_{R^n} \\: [Z] [S] [Y \\:|\\: Z, S] \\: d Z d S\n$$ {#eq-glgm-lik1}\n\nTo simplify the explanation and notation in this\nsection and the following ones, we will first rewrite the likelihood\nfunction in terms of the random effect $W_i = S(x_i) + Z_i$ and will\ndenote this in its vector form as $W = (W_1, \\ldots, W_n)$. Hence we\nwrite\n$$\nL(\\theta) = [Y] = \\int_{R^n} \\: [W] [Y \\:|\\: W] \\: d W\n$$ {#eq-glgm-lik2}\nIn this model formulation, we assume that $Y$ conditionally on $W$ is a\nset of mutually independent outcomes, hence\n\n$$\n[Y | W]  = \\prod_{i=1}^n [Y_i | W_i].\n$$\n\nHowever, unlike in the previous section, the distribution of $[W]$ is\na Multivariate Gaussian distribution with correlated components, hence\nwe cannot split the integral into separate univariate ones as before.\n\nMore specifically, $W$ follows a Multivariate Gaussian distribution with\nmean vector $0$ and covariance matrix $\\Omega$, whose $(i, j)$-th entry\nis\n\n$$\n[\\Omega]_{ij} =\n\\begin{cases}\n\\sigma^2 \\rho(u_{ij}; \\phi, \\kappa) & \\mbox{if }i\\neq j \\\\\n\\sigma^2 + \\tau^2 &  \\mbox{if }i = j\n\\end{cases}\n$$\n\nwhere $\\rho(u;\\phi,\\kappa)$ is the Matern correlation function with\nscale parameter $\\phi$ and smoothness parameter $\\kappa$; see\n@eq-matern.\n\nIn the next two sections we provide a brief overview of Monte Carlo\nmaximum likelihood and the use of Markov chain Monte Carlo to\napproximate @eq-glgm-lik2.\n\n#### Monte Carlo maximum likelihood {#sec-mcml}\n\nIn maximum likelihood estimation, we aim to maximize the likelihood\nfunction to find the parameters that make our data the most likely to\nhave been observed. Monte Carlo Maximum Likelihood (MCML) (see the\nseminal work by @geyer1991) is designed to handle situations where the\nlikelihood function is intractable. In the case of a non-Gaussian\ngeneralized linear geostatistical model, its likelihood function\ninvolves a high-dimensional integral which can be approximated using\nMCML.\n\nOne way to apply Monte Carlo methods in this context is through\n*importance sampling*. Importance sampling allows us to approximate the\nlikelihood function by rewriting the likelihood in a form that can be\nestimated using samples from an easier distribution, known as the\n*importance sampling distribution*. To this end, we then rewrite\n@eq-glgm-lik2 as\n\n$$\n\\begin{aligned}\nL(\\theta)\n&= \\int [W, Y; \\theta] \\: dW  \\\\\n&= \\int \\frac{[W, Y; \\theta]}{[W, Y; \\theta_0]}[W, Y; \\theta_0]\\: dW   \\\\\n&\\propto  \\int \\frac{[W, Y; \\theta]}{[W, Y; \\theta_0]} [W | Y; \\theta_0] \\: dW  \\\\\n&= E\\left\\{\\frac{[W, Y; \\theta]}{[W, Y; \\theta_0]}\\right\\},\n\\end{aligned}\n$$ {#eq-mcml1}\n\nwhere $\\theta_0$ represents our best guess of $\\theta_0$\nand the expectation in the equation above is taken with respect to\n$[W | Y; \\theta_0]$, which represent our *importance sampling\ndistribution*.\n\nLet $W_{(j)}$ represent the $j$-th sample out of $B$ drawn from the\ndistribution $[W \\mid Y; \\theta_0]$. To simulate samples from\n$[W \\mid Y; \\theta_0]$, Markov chain Monte Carlo (MCMC) algorithms are\nrequired and we explain more in detail in the next section.\n\nWe approximate the expression in @eq-mcml1 as follows:\n\n$$\nL_{MC}(\\theta) = \\frac{1}{B} \\sum_{j=1}^B \\frac{[W_{(j)}, Y; \\theta]}{[W_{(j)}, Y; \\theta_0]}.\n$$ {#eq-mcml2}\n\nAs $B \\rightarrow \\infty$, the Monte Carlo likelihood $L_{MC}$ converges\nto the exact likelihood function described in @eq-mcml1. The\nmaximization of this Monte Carlo likelihood is performed using an\noptimization algorithm that uses the analytical expressions of the first\nand second derivatives. This approach is especially useful for exploring\nthe likelihood surface, which can be relatively flat, particularly in\nthe space of covariance parameters. To improve the approximation of the\nlikelihood function in equation @eq-mcml2, this process can be repeated\niteratively, replacing $\\theta_0$ after each step with the estimate\nobtained from equation @eq-mcml2, until convergence is achieved.\n\nHowever, due to Monte Carlo error, the estimates after each iteration\nmay still vary considerably, making convergence difficult to reach if\nvery strict criteria are used. In practice, relaxed convergence criteria\nor a fixed maximum number of iterations (typically 3-5) are employed\nwith a sufficiently large number of Monte Carlo samples (e.g.,\n$10,000$). Under these conditions, we find that the procedure provides\nreliable parameter estimates, and the impact of Monte Carlo error on\nspatial prediction has been observed to be negligible.\n\n#### Monte Carlo Markov Chain: sampling from the predictive distribution of the spatial Gaussian process {#sec-mcmc-mala}\n\nBuilding on the outline of the MCML method from the previous section, we\nnow address the task of sampling from the distribution $[W \\mid Y]$ to\ngenerate the samples $W_{(j)}$ used in equation @eq-mcml2. To simplify\nthe notation, we will use $[W \\mid Y]\\$\\$ in place of\n$[W \\mid Y; \\theta_0]$, but it is important to emphasize that the\nparameters $\\theta_0$ are considered fixed when sampling from\n$[W \\mid Y]$. Since direct simulation from $[W \\mid Y]$ is not feasible,\nwe must rely on Markov chain Monte Carlo (MCMC) methods, which we will\nbriefly introduce next.\n\nThe Metropolis-Hastings algorithm} is a foundational technique in the\nfield of MCMC methods, which are widely used for sampling from complex\nprobability distributions. The primary goal of MCMC methods is to\ngenerate a sequence of samples from a target distribution where direct\nsampling is challenging, such as the distribution of $[W | Y]$. The\nMetropolis-Hastings algorithm, first introduced by\n@metropolis1953equation and later generalized by @hastings1970monte,\nachieves this by constructing a Markov chain that has $[W \\| Y]\\$\\$ as\nits stationary distribution. In what follows, we shall use $\\pi(W)$ to\ndenote the density function of $[W | Y]$ up to a constant of\nproportionality.\nGiven a current realization $W_{(k)}$ of the distribution $[W | Y]$ in\nthe Markov chain, the algorithm proceeds as follows.\n-   Propose a new realization $W_{(k+1)}$ from\n    $q(W_{(k+1)} \\mid W_{(k)})$, where $q(\\cdot \\mid \\cdot)$ is the\n    density function of a chosen proposal distribution.\n-   Compute the acceptance probability:\n\n$$\n    \\alpha = \\min \\left(1, \\frac{\\pi(W_{(k+1)}) q(W_{(k)} \\mid W_{(k+1)})}{\\pi(W_{(k)}) q(W_{(k+1)} \\mid W_{(k)})} \\right).\n\n\n$$\n-   Accept the proposed realization $W_{(k+1)}$ with probability\n    $\\alpha$; otherwise, retain the current realization $W_{(k)}$.\nThe algorithm ensures that, under certain conditions, the chain\nconverges to the target distribution $\\pi(W)$ as the number of steps\nincreases @roberts1996exponential.\n\nThe functions of the RiskMap package for fitting Binomial and Poisson\ngeostatistical models implement the *Metropolis-Adjusted Langevin\nAlgorithm (MALA)*, which is an improvement over traditional\nMetropolis-Hastings MCMC methods. Introduced by @rossky1978brownian and\nfurther developed by @roberts1996exponential, MALA incorporates gradient\ninformation from the target distribution to propose more informed moves,\npotentially leading to faster convergence and more efficient exploration\nof the target distribution.\n\nMALA combines the Metropolis-Hastings framework with Langevin dynamics,\nwhere proposals $q(\\cdot | \\cdot)$ are defined as:\n$$\nW_{(k+1)} = W_{(k)} + \\frac{\\epsilon^2}{2} \\nabla \\log \\pi(W_{(k)}) + \\epsilon \\, \\eta,\n$$\nwhere $\\epsilon$ is a step size parameter, $\\nabla \\log \\pi(W_{(k)})$ is\nthe gradient of the log of the target density with respect to $W_{(k)}$,\nand $\\eta \\sim \\mathcal{N}(0, I)$ is a Gaussian random variable with\nmean 0 and independent components with unit variance.\n\nBy leveraging the gradient, MALA can propose moves that are more likely\nto be accepted, especially in high-dimensional spaces or regions of low\nprobability density.\n\nIn the context of Laplace sampling for geostatistical models, the\n*Metropolis-Adjusted Langevin Algorithm (MALA)* is used to construct an\nefficient proposal distribution. The primary objective is to generate\nsamples from a conditional distribution of latent Gaussian processes,\nwhich is challenging due to high dimensionality and complex dependence\nstructures.\n\nThe Laplace sampling method, as implemented in the RiskMap package,\nutilizes a specific form of MALA. Here, the proposal distribution is\nderived from a second-order Taylor expansion around the mode of the\ntarget distribution $[W | Y]$. Let $\\hat{w}$ be the mode of this\nconditional distribution, and let $\\hat{\\Omega}$ be the inverse of the\nnegative Hessian matrix evaluated at $\\hat{w}$, which approximates the\nlocal covariance structure of the distribution. We then define the\nrandom variable $\\tilde{W}$ as\n$$\n\\tilde{W} = \\hat{\\Omega}^{-1/2} (W - \\hat{w})\n$$\n\nThis linear transformation is applied to decorrelate the components of\n$W$, making the MCMC updates more efficient [@geyer1994]. The function\n`Laplace_sampling_MCMC()` in RiskMap uses this approach where by at each\niteration the variable $\\tilde{W}$ using the MALA algorithm, and samples\nfor $[W | Y]$ are then obtained by inverting the linear transformation\nfrom the above equation. The logic behind using this approach is that it\nallows the proposal distribution to adapt to the local geometry of the\nposterior, thus improving convergence properties and reducing the\ncorrelation between successive samples (see @christensen2004).\n\nOnce the MCMC algorithm has completed all iterations, it is important to\nensure that it has converged to the target distribution. The diagnostic\nmethods listed below can be used to assess convergence using the\nobtained MCMC samples.\n1.  **Trace Plots**: Plotting the sampled values against the iterations\n    can help visually inspect if the chains have reached a stationary\n    distribution. A well-mixed chain should appear as a \"random walk\"\n    around a stable mean value.\n2.  **Autocorrelation Plots**: These plots measure the correlation\n    between samples as a function of the lag between them. Low\n    autocorrelation across lags indicates good mixing, suggesting\n    convergence.\n3.  **Effective Sample Size (ESS)**: The ESS measures the number of\n    independent samples that an MCMC chain is equivalent to, accounting\n    for the autocorrelation in the chain. It is calculated as:\n\n$$\n    \\text{ESS} = \\frac{N}{1 + 2 \\sum_{k=1}^{\\infty} \\rho_k},\n    $$ where $N$ is the total number of MCMC samples and $\\rho_k$ is the\n    autocorrelation at lag $k$. A high ESS indicates that the chain has\n    good mixing properties and the samples are nearly independent. The\n    summation of autocorrelations up to a sufficiently large lag is used\n    to estimate the reduction in effective sample size due to the\n    dependence between samples. A small ESS suggests high\n    autocorrelation and that more samples are needed to achieve the same\n    precision as a set of independent samples.\n\nA high ESS (Effective Sample Size) indicates that the chain has good\nmixing properties, meaning the samples are nearly independent. The\nsummation of autocorrelations up to a sufficiently large lag is used to\nestimate the reduction in effective sample size due to the dependence\nbetween samples. A small ESS suggests high autocorrelation, meaning more\nsamples are needed to achieve the same precision as a set of independent\nsamples. In addition to those, other diagnostics can provide further\nassurance of convergence. For example, the Gelman-Rubin diagnostic\ncompares the variance between multiple chains to the variance within\neach chain; a diagnostic value close to 1 indicates that the chains have\nconverged to a common distribution [@gelman1992inference]. Also, the\nGeweke diagnostic tests for convergence compare the means of the first\npart and last part of a single MCMC chain. If the means are not\nsignificantly different, it suggests that the chain has reached\nstationarity [@geweke1992evaluating]. Using a combination of these\ndiagnostics can be used to assess whether the MCMC algorithm has\nadequately explored the target distribution.\n\nIt is important to point out that in MCMC algorithms, to the quality of\nsamples we need to carefully consider these three control parameters of\nthe MCMC.\n-   **Number of Simulations**: Increasing the number of simulations\n    allows the algorithm to explore the posterior distribution more\n    thoroughly, reducing the variability in estimates. A higher number\n    of simulations typically leads to more accurate results but also\n    requires more computational time.\n-   **Burn-in**: The burn-in phase refers to the initial set of\n    iterations where the Markov chain has not yet converged to its\n    stationary distribution. These initial samples are discarded to\n    ensure that the remaining samples represent the target distribution\n    more accurately. Properly setting the burn-in period helps avoid\n    bias due to initial conditions.\n-   **Thinning**: Thinning reduces autocorrelation by only keeping every\n    *n*-th sample from the chain. While this decreases autocorrelation\n    between retained samples, it also reduces the overall sample size.\n    Thinning is used when chains exhibit high autocorrelation to ensure\n    a more independent set of samples is analyzed. Initially, these\n    values can be set based on prior experience or general rules of\n    thumb (e.g., a burn-in of 10-20% of the total iterations). In the\n    next summary section, we provide more details on specific\n    implementation of these in RiskMap.\n\nFor a more thorough and complete overview of MCMC algorithms, chapters\n10 to 13 of @gelman1992inference are a recommended read.\n\n#### Summary with example {#sec-summary}\n\nIn summary, here are the steps required to perform Monte Carlo Maximum\nLikelihood (MCML):\n1.  Start by selecting an initial guess for the model parameters,\n    denoted as $\\theta_0$.\n2.  Simulate Samples from $[W \\mid Y; \\theta_0]$ using MCMC methods.\n    Perform a check on the MCMC samples to assess convergence of the\n    MCMC algorithm.\n3.  Compute and maximize the approximate likelihood function in\n    @eq-mcml2.\n4.  Set the newly estimated parameter as $\\theta_0$ for the next\n    iteration.\n5.  Repeat 1 to 4 until convergence is achieved.\n6.  Monitor the estimates for convergence. If strict convergence\n    criteria are set, Monte Carlo error may cause fluctuations, making\n    it harder to achieve convergence.\n7.  Perform additional iterations, if necessary. For inference on model\n    parameters, continue iterating to reduce Monte Carlo error. For\n    spatial prediction, a pragmatic approach may involve stopping after\n    a second iteration with 10,000 samples, as prediction is less\n    affected by Monte Carlo error.\n\nIn RiskMap, steps 1 to 3 are automated (with the exception of the\ncheck on the convergence of the MCMC algorithm in step 2), while steps 4\nto 7 require manual implementation. In @sec-liberia-estim1, estimation\nis performed using a geostatistical model fitted to prevalence data. The\n`par0` argument in the `glgpm()` function allows you to specify initial\nguesses for the model parameters $\\theta_0$. If no values are provided\nfor `par0` (as in @sec-liberia-estim1), the following defaults are used:\n-   The initial guess for the regression coefficients $\\beta$ is set to\n    the maximum likelihood estimates obtained from a standard\n    generalized linear model (GLM), i.e., a GLM without random effects\n    or overdispersion.\n-   The initial values for both $\\sigma^2$ (the variance of the spatial\n    Gaussian process) and $\\tau^2$ (the variance of the nugget term, if\n    included) are set to 1.\n-   The initial guess for the scale parameter of the spatial correlation\n    function $\\phi$ is based on the 0.1 quantile of the distances\n    between all pairs of locations.\n\nIn our experience, this set of initial guesses works reasonably well.\nHowever, more iterations of the MCMC algorithm, as suggested in the step\n7 above, are generally recommended.\n\nAn alternative approach for setting initial guesses for the covariance\nparameters $\\sigma^2$, $\\tau^2$, and $\\phi$ is to apply an interpolation\ntechnique to the variogram, as proposed in the seminal work by\n@cressie1985. However, in our experience, this approach does not\nconsistently provide better approximations of the likelihood function\ncompared to the method mentioned above. This may be due to the\ninstability in estimating the variogram based on residuals from mixed\nmodels, as well as the sensitivity of empirical variogram estimation to\nthe chosen distance breaks.\n\nTo better illustrate some of the points above, we continue the analysis\nof the Liberia data from @sec-liberia-estim1. Diagnostic summaries on\nthe convergence of the MCMC algorithm can be obtained with the\n`check_mcmc()` function by passing the fitting model `fit_liberia` to the\nfunction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_mcmc(fit_liberia)\n```\n\n::: {.cell-output-display}\n![Trace plot (left panel) and autocorrelation function plot (right panel) for the averaged spatial random effects from the river-blindness data analysis. The title of the right panel also shows the effective sample size of the 1000 Markov chain Monte Carlo (MCMC) samples. The MCMC samples are obtained by running the MCMC algorithm for 12000 iterations, with a burn-in of 2000 and thinning of 10.](03_model-fitting_files/figure-html/fig-check-mcmc-mean-1.png){#fig-check-mcmc-mean}\n:::\n:::\n\n\nThe plots shown in @fig-check-mcmc-mean are for the MCMC samples of the\naveraged spatial random effect, that is\n$\\bar{S} = \\sum_{i=1}^n S(x_i) /n$. Performing the check on $\\bar{S}$ is\ndone to avoid the need of checking the convergence for each individual\ncomponent $S(x_i)$. However, one of the risks of doing this is that if\nfewer components of $\\bar{S}$ have not reached convergence this may not\nbe shown through the inspection of the samples for $\\bar{S}$. However,\nthis is an unlikely scenario when using the type of MCMC algorithm\nimplemented in RiskMap (see @sec-mcmc-mala). Nonetheless, if one wants\nto check the convergence for individual components this can be done as\nfollows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_mcmc(fit_liberia, check_mean = FALSE, component = 10)\n```\n\n::: {.cell-output-display}\n![Trace plot (left panel) and autocorrelation function plot (right panel) for the tenth component of the spatial random effects from the river-blindness data analysis. ](03_model-fitting_files/figure-html/fig-check-comp10-mcmc-1.png){#fig-check-comp10-mcmc}\n:::\n:::\n\n\nBoth @fig-check-mcmc-mean and @fig-check-comp10-mcmc, shows a reasonably\ngood mixing and relatively low correlation in the samples. We point out\nthat the number of MCMC samples in `glgpm()` are set through the function\n`set_control_sim()` passed to the argument `control_mcmc()`. By default\n`set_control_sim()` uses 12000 iterations, a burn-in of 2000 and thinning\nof 10, thus giving 1000 MCMC samples. This configuration can be enough\nfor the first run of the Monte Carlo maximum Likelihood (MCML) method,\nhowever it is advisable to increase the number of iterations to obtain a\nlarger number of samples with reduced correlation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Update the guesses for the model parameters\npar0_liberia <- coef(fit_liberia)\n\n# Refit the model and increase the MCMC samples\nfit_liberia2 <- glgpm(npos ~ log(elevation) + gp(nugget = TRUE),\n                      den = ntest, data = liberia,\n                      convert_to_crs = 32629,\n                      par0 = par0_liberia,\n                      control_mcmc = set_control_sim(n_sim = 110000,\n                                                     burnin = 10000,\n                                                     thin = 10),\n                      family = \"binomial\", messages = FALSE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_mcmc(fit_liberia2)\n```\n\n::: {.cell-output-display}\n![Trace plot (left panel) and autocorrelation function plot (right panel) for the tenth component of the spatial random effects from the river-blindness data analysis. The Markov chain Monte Carlo (MCMC) samples are obtained by running the MCMC algorithm for 110000 iterations, with a burn-in of 10000 and thinning of 10. ](03_model-fitting_files/figure-html/fig-mcmc-10k-1.png){#fig-mcmc-10k}\n:::\n:::\n\n\nThe code above performs an additional step in the MCML estimation, using\n10,000 MCMC samples. As shown in @fig-mcmc-10k, these MCMC samples\nexhibit good mixing and low autocorrelation, which indicates that they\nadequately approximate the likelihood function of the Binomial\ngeostatistical model. Although additional MCMC iterations could be run\nto obtain estimates closer to the true maximum likelihood estimate\n(since we are approximating the likelihood function and not obtaining\nthe exact MLE), we choose not to do so here. This decision is due to\nboth the computational time required and the minimal impact of Monte\nCarlo error on spatial predictions in this case.\n\n#### Alternative approaches\n\nIn the sections above, we focused specifically on the implementation of\nthe Monte Carlo Maximum Likelihood (MCML) method in RiskMap. However,\nother approaches are available, some of which are computationally more\nefficient than the MCML method we have illustrated. Our preference for\nthis estimation method is based on two main reasons: 1) it delivers\nrobust performance across a wide range of data scenarios, and 2) it does\nnot require the specification of arbitrary prior distributions when\nprior information on the model parameters is unavailable.\n\nAlternative methods worth mentioning include the\nexpectation-maximization algorithm for maximum likelihood estimation\n[@zhang2002], integrated nested Laplace approximation (INLA) [@rue2009],\nand implementations of the Metropolis-Adjusted Langevin Algorithm (MALA)\nfor Bayesian inference [@christensen2006]. While these methods are\nvaluable, explaining and comparing them is not our focus here, as it\nwould detract from the practical orientation of this book. The *RiskMap*\npackage itself will continue to evolve as computational improvements are\nmade, and future editions of this book will update these sections\nwithout affecting the applied analysis content.\n\n### The Hat matrix in linear geostatistical models {#sec-h-matrix}\n\nWe consider the geostatistical model\n$$\nY_i = d(x_i)^\\top \\beta + S(x_i) + Z_i\n$$\nwhere $Y_i$ is the observed response at location $x_i$, $d(x_i)$ is a\n$p$-dimensional vector of covariates, $\\beta$ is a $p \\times 1$ vector\nof regression coefficients, $S(x_i)$ is a spatially structured random\neffect, and $Z_i \\sim N(0, \\tau^2)$ is independent Gaussian noise. The\nmodel can be rewritten as\n$$\nY = D\\beta + S + Z\n$$\nwhere $Y = (Y_1, \\ldots, Y_n)\\top$ is the \\$ n \\times 1\\$ vector of\nobservations, $S = (S(x_1), \\ldots, S(x_n))^\\top$ is the vector of\nspatially dependent random effects, $Z = (Z_1, \\ldots, Z_n)$ is the\nnoise, and $D$ is an $n \\times p$ matrix of covariates given by\n\n$$\nD = (d_1(X), \\ldots, d_p(X))\n$$\n\nwith each column $d_j(X) = (d_j(x_1),\\ldots,d_j(x_n))^\\top$\nrepresenting the values of the $j$-th covariate across all locations.\n\nThis formulation accounts for both fixed effects through \\$ D\\beta \\$\nand spatial correlation through $S(x_i)$. The covariance matrix of $Y$\nis\n$$\nV = \\Sigma + \\tau^2 I\n$$\nwhere $\\Sigma$ is the spatial covariance matrix of $S$. Assuming the\ncovariance parameters are known, the generalized least squares estimator\nfor $\\beta$ is\n\n$$\n\\hat{\\beta} = (D^T V^{-1} D)^{-1} D^T V^{-1} Y.\n$$\n\nThe predictor for $S$ is the conditional expectation\n$E[S(x_i) \\: | \\: Y_i]$ is\n\n$$\n\\hat{S} = \\Sigma V^{-1} (Y - D\\hat{\\beta}).\n$$\n\nso the predictors for $Y$ can be written as\n\n$$\n\\hat{Y} = D\\hat{\\beta} + \\hat{S}.\n$$\n\nThe hat matrix, which projects observations onto the fitted space, is\n$$\nH = [D - \\Sigma V^{-1} D] (D^T V^{-1} D)^{-1} D^T V^{-1} + \\Sigma V^{-1}.\n$$\n\nThis matrix is symmetric since it consists of symmetric components,\nsatisfying $H^T = H$. It is also idempotent, meaning $H^2 = H$, which\nfollows from the properties of projection matrices. The diagonal\nelements $h_{ii}$ represent the leverage of each observation,\nquantifying how much each \\$ Y_i \\$ influences its own fitted value. The\nrank of \\$ H \\$ is at most \\$ p \\$, constrained by the rank of \\$ D \\$.\n\nUnlike in ordinary least squares where the hat matrix is\n$H = D (D^T D)^{-1} D^T$, here it depends on $V^{-1}$, accounting for\nspatial dependence. Since $V \\neq I$, the hat matrix represents an\noblique projection rather than an orthogonal one.\n\nThe residuals, i.e. the estimate of $Z$ are given by\n\n$$\n\\hat{Z} = Y - \\hat{Y} = (I - H) Y.\n$$\n\nWe note that the covariance structure of $\\hat{Z}$ is\n\n$$\n\\text{Var}(\\hat{Z}) = (I - H) V (I - H)^T.\n$$\n\nHence, the estimated residuals from a linear geostatistical model do\nhave a correlation structure which relates to the chosen spatial\ncorrelation structure in $\\Sigma$.\n\n## Review questions\n\n-   Describe how you would perform exploratory analysis between counts\n    data and covariates, distinguishing between unbounded counts (e.g.\n    Poisson), bounded counts (e.g. Binomial) and binary outcomes.\n-   Define the theoretical and empirical variogram, making appropriate\n    use of equations.\n-   How do we use the empirical variogram to test for spatial\n    correlation? What are the limitations of this approach?\n-   Define the class of generalized linear geostatistical models and\n    list all the assumptions.\n-   Explain intuitively what are the computational challenges related to\n    the fit of geostatistical models and what approaches can be used for\n    parameter estimation.\n\n## Exercises\n\n1.  Consider the Binomial mixed model with linear predictor as defined\n    in @eq-linear-predictor-glmms-ch2. By editing the code for the\n    simulation shown in @sec-overdispersion, generate a graph as in\n    @fig-var-bin-glmm under the two following scenarios: $i$)\n    $\\tau^2 = 0.2$ and $n_i=100$; $ii$) $\\tau^2 = 0.1$ and $n_i = 1$.\n    How does the variance of $Y_i$ change under $i$) and $ii$) in\n    comparison to @fig-var-bin-glmm? How do you explain the differences?\n2.  Similarly to the previous exercise, consider a Poisson mixed model\n    with linear predictor\n\n$$\n        \\log\\left\\{\\mu_i\\right\\} = \\beta_0 + Z_i,\n        $$ where $Z_i$ are a set of mutually independent Gaussian\n    variables with mean 0 and variance $\\tau^2$. Using the code shown in\n    @sec-overdispersion, carry out a simulation study to compute the\n    variance of $Y_i$ and generate a graph similar to @fig-var-bin-glmm\n    to compare the variance of the Poisson mixed model with that of a\n    standard Poisson model. Generate the graph for different values of\n    $\\tau^2$ and summarize your findings. NOTE: In this simulation the\n    offset $n_i$ can be set to 1.\n3.  Create an R function that computes the *cloud variogram*. As\n    explained in @sec-expl-spatial, the cloud variogram is obtained by\n    plotting $\\hat{V}_{ij}$ (see @eq-hat-squared-diff) against the\n    distances $u_{ij}$. The function should take as input a dataset\n    with three columns: the variable for which the cloud variogram is to\n    be computed; and two columns corresponding to the location of the\n    data. Then, use this function to create the cloud variogram for the\n    model for river-blindness in @eq-liberia-bin-mixed-elev. How does\n    this compare to the empirical variogram that takes the averages\n    within predefined distance classes, as shown in @fig-liberia-variog?\n4.  Fit a Binomial mixed model to the Liberia dataset on\n    river-blindness without any covariates, i.e.\n\n$$\n        \\log\\left\\{\\frac{p(x_i)}{1-p(x_i)}\\right\\} = \\beta_0 + Z_i.\n        $$ Making use of the R code presented in\n    @sec-empirical-variog-bin, use the function `variogram()` to\n    generate the empirical variogram for this model and compare this to\n    the empirical variogram of @fig-liberia-variog. What differences do\n    you observe?\n5.  Fit a Poisson mixed model to the anopheles mosquito data using\n    elevation as a covariate, i.e.\n\n$$\n        \\log\\{\\mu(x_i)\\} = \\beta_{0} + \\beta_{1} d(x_i) + Z_i\n        $$ where $d(x_i)$ is the measured elevation at location $x_i$.\n    How strong is the overdispersion in the data? After fitting the\n    model, extract the estimates of the random effects $Z_i$ and compute\n    the empirical variogram with the 95% envelope for spatial\n    independence. Repeat this for different classes of distances by\n    changing the input passed to `breaks` in the `variogram()` function.\n    How do the different specifications of `breaks` affect the results?\n6.  *Parametric bootstrap.* Using the model fitted to the Anopheles\n    gambiae mosquitoes in @sec-anopheles-fit, simulate 1000 datasets\n    using the `glgpm_sim()` function and estimate the model to each of the\n    simulated dataset. Use the resulting 1000 estimates to compute\n    95$\\%$ confidence intervals for each of the model parameters and\n    compare this with the confidence intervals obtained from the model\n    summary.\n7.  In Section @sec-glm-parest, we explained that for a linear model\n    with one observation per location, we cannot simultaneously estimate\n    both the measurement error variance $\\omega^2$ and the nugget effect\n    variance $\\tau^2$. However, if $\\omega^2$ is known, we can fix this\n    value and estimate the nugget effect. Suppose that for the Galicia\n    data, the measurement device has a known standard error of\n    $\\omega = 0.15$ on the log-scale (i.e., $\\omega^2 = 0.0225$). Fit\n    the model $$Y_i = \\mu + S(x_i) + Z_i + U_i$$ using `glgpm()` by\n    setting `nugget=TRUE` and `fix_var_me = 0.0225` in the `gp()`\n    function, with $\\kappa = 1.5$. Compare the estimates of $\\sigma^2$\n    and $\\phi$ with those obtained from the model without the nugget\n    effect (Equation 3.16). What is the estimated nugget variance\n    $\\hat{\\tau}^2$? Repeat this analysis for different values of fixed\n    measurement error variance: $\\omega^2 \\in \\{0.01, 0.05, 0.10\\}$. How\n    do the estimates of $\\sigma^2$, $\\phi$, and $\\tau^2$ change as the\n    assumed measurement error variance increases?\n",
    "supporting": [
      "03_model-fitting_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}